apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/part-of: full-stack
  name: frontend-service
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-service
      app.kubernetes.io/part-of: full-stack
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: frontend-service
        app.kubernetes.io/part-of: full-stack
    spec:
      containers:
      - image: quay.io/isequeir/frontend-service:ishitasequeira-patch-7-24a74f15b34b833b33633c375e2dcbf1cf5e72b5
        imagePullPolicy: Always
        name: frontend-service
        ports:
        - containerPort: 8080
        resources: {} 
      serviceAccountName: default
status: {}
