apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBeYULM1G3UsXp8d0OxCzA/FIbZLBMb45xmHEloZG7GsNCF8hiJW/KeOYs8KD3QiY0S16gI+xV1tT9+I9icQ+J6XFWtWRUIO4eUICCPfDSjEXzoHT8HV1uvx4fsrUX8h/u0igflu0OyoJETItkHUT0uNfzE3cCiPC6/fYpzC7tJ3AHp1B/kG83cjep+fCuEDiIEn+akITs4WOlBKbs23qhqv7kKO5IRdzU9/uBdGZSndgkWEWW589dhSELXL0VJncbXK1fvQiWJB6KA4EKRkF9NMNPQPWxuvurvkGmJE1Gd5jQHmeSOEKlGFRBV5BLnhmmAGdWnur8rQlNlGwNXy9equkXzHoOySSyvDF7VGcSWg+HLDfAwR/FkScJDZGdCThH3NrdkCRw0+t8W5rBKmKAQ3BODnxU9aYEnfpWpKU4DPM3yy9xf6oy7IIgC7GW4j7TAxK4kH2gkroDByXWCBsjv8Ubls7lQ1BfJ9tnTxcseQY4fXWkEPG9+i0i2ZKfVX83Ek5NTgHrL7PKc/iBB9lQO0XA1UAqmf8Zo1QwjB1ziKGc8/Hez1nYjTxtyS4k8wTi45NgA9JMV8cODy9lAlAKgPw5kRn8sZOWIE6t1SJsrCSY7a8CEIZe1HjddDL0TWvfDZux7FpJ+9CblFpBE6TC8bpcIDdJ5NqWfxXcsxckF/sE1tDdoSlV4wfw/PsAp0bs3dWXzOhpgsx/rOX9LzcHtxwBPbTNvSdmao99H90l1EeWHCLj6DciG1i0TQqoPYohx6u8nW85CMJP6xaZARpEy0oqUXfRKBnzN2P0yLcA1FPI+6/POcpPjrrKnL7B/VlBiYoeb+4OLMwaLRxWLamlYcdlVab8+wmc6ocwmkK1bHp+3ldH1zuYUi/iaGn2vMYMYknnDkKS96tNXDl/Im2ObJ2Ibz9RSdVaJZCYV5+TP+jmMooQagxzQ9QM1
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
