apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA0d7QEyIoy+iQGOCkHfcSp+C3eIPDFs54NB2iJDk8TWnljfXXKsDO3H/w5wzVNCTudRA40RjUhLBlE8e1eDNoIPu5ZAFWwULgGVYV69RTMM4yykxabgnq7EBTPPDhJNQMKH/j00SuUFhrBZu8R0H9q5XQFE9uwVFzXfB7G35iMaM90pRaUvUvfm8VoVlsLmi7Nmm+VNm5XZZnPjaw+iQDXzkdslQ0Los6VCulGBhmSt1BaZuKy+pwSZ3ImrsF7uKCDMZJm8O0yiP1DB/sj+rdjokCd9UUux/7OgcFqcqs2yJUeRFoaBC/n2pZEZz8aGNrp0FE5fTYfXbaGJKBt161efv8rVniMDc0GJ7hRt+QBoQf7Z3JpvxrjjFTJkZsoqfC1WZY37eUhqHZ46U6gaClCgyJe/4LnOu2REsUrueD9qC8K6S75bhzmhKFIpsuQEA5hMGl0WFetNpQySG2cmrFtTpbRhifGVG+m/F874mVhnM0EjFTQFbm5Lvqi5kkXZtuemGH0c4mipI74pYyLCagr9wL/qun4Iz4qoqrV68n9MvKopo9ZzLqWLO7bBzyqORp86rl5/J4fe5W5qdTX6E7d/9qrtcde4uVDHKCVeB0NUZ8nf4Zu/+1U0pf5MKqBeph4f+uTXqE83dFC5eo/Mxw66NeA1QA1f9Z2iFP4zFXEOQr0GTMihBpUFip3CVxMysv/T9ks1K7snqCK5JraSWRMbbIrIXTojasjTYMF7A2BHdPS1jXgC3I659ifVPO6jggDKONPCO2QvUZNzTUySW4QBIkCwS4ZtO8jCviS783WvdEp3Iv5XejdbWYCBy2LSHLlEpf+/dUT5ib0iYm8xUcZ2Z/PcZMbrGUJNQBZ743cRqF+sd8ER2dC/TM/+RkH/FE7gAHSd+gzs2SlkxUo/6LRLBeK4Ubj+DAfVeIztkhD4f1oy+4Q8BzmPKKn
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
