apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAW7fewCmVBVqv2E6J4Qq/5xOWh4Th8H5UQW1XS2JQovaMKLNp6Oih8mi/qUbahd/9m0EQTNIBeAjKdIHibrM9D9O+htkMqzhzXxWf5Gy5m04uwU8/a7C31D+UoLwT6COVolB5Gr2GtX9VARUAlP2q2PCgG/vchTUc1cgk0f8E9njNURYb6iOQ0bl+p40KYaO6Q5+YEBkhZQfb9BbXP/Gz/castSx5VCXrWCfOmKVAc26ubIjtVA3bo2Fu/pzJfwyK71U1axf7K5Ri23L52kHKDLmySQ2AVlCI3RNyBASI1w0l4lSB/MopPEIa7XitAg5uc0DShDDVRYEHfx+CJ4TUd7fA7UE57+hTNCZxMoFBxGlMOeCMnWGsXF7OLymrkqiG8CHIkMPZKuTqdrMyqMyYo3jRoom3bHNPC03sYDi5tlO1rPwpmqdVBi9EbkiuHDPDwnN8KC3g616aPc7EFMpJue5wGxwn2PRxf7QGj3Lnc9J0Irr3brI3wvTwJTx7ZsGmej1ZR6vdEHLbD9Srff+Y0uMgCyOwOxQTLj6ltkRjDW2IRHCpf01RrbdXwD8ug5JFKQ9gjouIDF4uE/RSoMpuLU2GqPHeGYy6Pg8uY2M+mXByxSoLLgPvO+tnhm7IA+3C2cIKEWvOPP9qJ19UOAaCLth/A6tiRF+j0QQC/KsF9wpnJyUl6CdeBctnbs4pbWZ4uaCf0gx6XS2vOLjxYDveDggpe5LFweYPly6iY3LihzjaFQA8nAp31aGvlGlUMsaZg3ClLhPFnpDuM9i/dIjJ9LCobJ/Wgf5VXVJaEpOpSCfDa3GSUaSP9TNwNwXX8TaFcoL73XKnJwGj+MS3ePJsc5igmcuwtebAJzFrRsxR901Mq8pc1dVqPmH3DruAPm9EimTKvEud70KGTPCFZvt+dTblsBm3IxE3IaNqQHenpjdZSCfhW/0QbC/ok
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
