apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgALA+Gj1gFYfERN/6Bs0cYq054X2EKehPW8VkzfDbM291zl7S40Cn67yNiu3PpdO0zBqHNOCPmfUIqYsTO8h1hhMUgCpctlNfoBnSESbbO7vQG+FA0gnMwIwAwyDULA6IUAPxnX9Y6xBZXDYoB1FpcqKsfBrxcZ64MI060WeyEJDzg+wBXZSJdKjgOTFw5lEGfAcuoGZftKBtHLF6YJ/925huZoFDzCayCY22BRVjiKIbj5rX50ViPNTCxAkyxQRZgZLuVJJ0QDK19JXvhu3rQWg47dH/skuELr165lnB7DDdZLnMDV+qEUpfdVKtBjuCfjWjSrIiS4+tbBnsAQTbC/8ydQ6OyX6V2kmaIswwWkpZaGaNEEynMmRd4WoKOK25vodHT1Qk3vBYsWe9vNibJWLQdnVv5y3NHQroiQDDQJl59zQrS0jYrSgPlCtkFB+ezb241mh232Sp7z5G27KQ3hKgR64kB+z0hP3LP2bysHRldBd1kdfIfx/pryAZx+d9kyL04X2aAAIsH9hZe+L4oiYuXWHz5/H26wLEVEPORmlGEMxUV4KJ+tN2XOord4XwA2w1L4XhMeHuWMGc04wYjzV01OEHna8GFq5FJEXqNWM11jEUsZ7J3keCiSEVTxlkV67L+V0QyfQ9EpNhuZ1FzpAn893OIeFANMuvdZvFN8RDIVWAC02H9uuY/CPRGN0Q3qXWSrQgeGH9FhwJctnbEdCFU/GRoJCYo46swgCdoZPgzFptG6ASfPNvdx2ao60gTII6oHqrbRYr7O/PE348yxnNhDR1PprTSTN6GK0MKGwUzfIks7/XrW3CH1rQx42uCFlE3s32aIzkpVAQJj1RXboXnsEbnWsTHsi4ZthARbzBVxxgk6bh80QgmYSQZWiK0XlDiqHc2XhnNgMksSOmtqX96/zYDnX2JDMu5NmfX7EVs1Y6RyqxjS5O5R
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
