apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCsB+8YjDB7JX6rI/C+A0Xr9r0IEnpdxLZLDY+ohTplQY5IfVOUMhIW+M9UIz8OIzwdK9Jbsjm5gG2/katuq2w1Qw9NgQK72l6ew+16PwKVWfr+0w7c+ktmIshk/PdrfAxbiyZMJFjSkpKsUzglAGf5wdopOsUIK5We7/IytHC6H/PSFyRKuSlZPj+D07xf/N7WlQJ+yoI64QhL/FR2RU3R4oI+l/P38lM5IR/B6KbKtzEdO3EGqLojKXCk/SXLhjo0cchdHjD3oeRQuX7AlV8z4Hjxx/07QOho8KVodwmjuG3doQjUEq+VAU07n9isZ8SE5yhOFAvHe0htY2FVgntJEbay4FMpbJ8yYvJARa0LRcmRqxMkLj3wPBQwJk6D4SXiHVfu3KB63D4ORYIbEkP13i8jwqZv+iDgC8eHtvUO+7aiZv4GJkyyVhgrGj5UdJLVVxQbrj8inSKMOH61c39ETa2Kg8vW+7dz+CCkewyHaou3Nis8cVu4VtSGVCT0Dw4Om/Ig+qeNXPh1lkqhA80naOIRGF1lEJDpedS4SnnVEkVMUgb4Kp+SPPCr75yR9fj6FvmHG4jH8064cJtZGgtkIqTKZdIZ9kzf+aXgnifVB5vxVJSVzIRdQy4LX3zlfHog9mvGDxa9PmrmL4TBI4fi3XTWohk9S6DCOUXFEyj3Qsoi6szL56n4Mck5OPUxMygYZfEbkOTGk0d3HYZ9xx4XinpkOnLg/NX0bnyEaWIyMnC8E78cYjL7Q15ArO1zvOm/GoP0lQHLUthO7KNX6WNl92WCr51KJe/hcz/xT43Wc0uDPelzjTdZa2n5srYhQQanowc7o0m9ipkhGhXfQY/2sdP2ZMyZ35+TGSOvdxc/vZi62dv/5rbuEsD28RSXrEAv+l6QYutdBk/nDTWQCTMBb6dTURQ4b9z3XxnYJqhTviZV813ynFfa2YXU
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
