apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgChwHsH7PxyhOk2f86rj/xo6L+PuvsjFohQdEdQrxiR/bzQ1hLgECUqRxK5CWPHYovf6TAozN/Q+b/8WKucVmIrSsCRmxJSY3jeaoBG3400mj2Lx+8UhyVOpRlIegWSKIypkCwbKVXQxFjM8zEEhhjJI6TfbFrcktObzqrxikmUzVlqmW4IBxo2TArxdZaLmCo5F0TX0qDuuFmg56l7QgkozplMTssypZqTxbRJQ9Wr4yw6/FRAfYsal3jPzpvQkYxn5x6ViN/MX62U881EsIdHadT9QV7IqupjJd0f08jJNAHg2akhyoRYCGb1e7BqImZ0iWor+XHTsf+3ao3EB85rda82Bjc51xb7i9vPKnd/ppFGvPF2PI46ctCaS9hOzzkhyjMQJx4KflFaYNZUZQQ66vwpKT0RlPjB+BZYhHftXGkWuNYBhRsTQfP9fj6G+xc55n1Wf6c9d+0MLj9UYWEnq9H4pWMeHmWBcYNiCC7GoIzgp4oO6dlSWszKSK9Qenqxyxgz5DRPA1wf0aeLki2j4Ql3qsnadQI7WeqcNYtiNK2M3QrhjNW9NsDpSfxunAhXCO7zHf88HNj9o3EUVnzpyVzX9GhJEeDff6wsDSoDP/KKM9SIsqPaGhJS+Ai4OGMDVjkuioLU2F2FXRt9Coik/HqVLiFnsQIUcoqfvh+ps1QuuRExXg7nfl+hTQlc8tyFR/nFPfkGQ/q+Xwttu8EYne4paFdUsfqiYVvYL0S6pGgliJzpMQ2QMLfBu5K/B5bemeV1/CqLwGT/1MsV/EhJfgbakCGVrGYmg0OeaZvmBTDXWhsI8PMYlJi5tZ/0UtbK7W/Dmu8Oigo5GOBr6vUtsh3UsarH6VZmCysBJ1ecZh8W41aE9gSWeRlkaK5fzWavN4YbRfI+idQv2kCYI6j6pHxudK1OaBoXsQGgXIhvHsoIkWUisG4phsgw
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
