apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAAa/2lP5+fMxt1CrCv4dQFRAkxCMY9T53pZMXFTXPtZyhl47YVlxix/WRkT2ta0hyIku2o03Wy8oCSFHOvaXcDu0pqi7bB2DV370529telgwH/p5jSy1oyWkA4AoO9pUlYbCbGSFNcX4ozSxA7Y8zScZZ2RdxLv4yShfqVSlH/P7LO/BlFn0YfHgxZJI2cwbzQbNZj1IBnnvtuAtPwWMY2SyP9XD+GnD5nQMeoLLTnVR24vZKUOH4Sk1YMxg+SULw5hEB+yvJZzuwqbaqWocZYgFSdg9qmP7Ujfcjqy/LSlvDJpH7SKJOAdoqhdZJkw9/J++k64NX/N5USwH8q/JNMn1aPTRo6FU0JFdmZf+gfSLfHtDHD5PFBOym0z00giXhGsGdFqfO6TSgdb5WJOJFB78b+sPr9sjD8EVnZpMrIynojfGFt6zjP5G19Q8dQrY38frNHsPfqe4a5o1YptD9FWjabihsprjVupnm90VwqvEBbiZbvnDuxKIsq2amB9ZFUJZ+3mgXeIQOmM+bI3uDxB8gdGW3kN+2ccW/7X5Ji7+EJ3ziQiZEdhgNjrc5EZmgmIJXtoK4Rar2YaVBQvnkEQXLJvCepmgspH3nej6/hY1TzDQwCSOtgKd5EJ6zI3xfHVf1A4gDG50hxr1OI5m5Uu8sri02Hxcctcu8C/4bYNaaZhrxGNCm1RpiYxA74UpbeNFA05moxXjckr/ZVOigwgncGE5IScTeRK7Bv4tuqguPVeVSuxOCgb+FrnH+5nQOdBjIk1OEbBUeSZE9TnyHebmkX7IbXvZyLn9BOacQYQ4qjOU9Oju+EJ/VoZ5IqhBBv93xea3oA+uLe5L8BkNtoXodf6rE+3pGewhtp1jPaomZD2AIE5q1pdDCDdaSL+SNbi0NP3STqW8QhsT/2nTRu/6numDudZb9NLxnvxskJMao2FZfO3RmYOJbw
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
