apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCJ+/QKOHl7BdzmliQZ2bE6ejt4qJo/jiGimjy7y67noPxzcueX+OtCb3C+i+gpyCUpPiUHe7n/PUs4Dkl2vILy63KyHE0mp3GZK57lXWmxfDLVv8RPpk6CiOSV31ItMe0y2e7iJxh9f9GN/slJlLLR7zmHHpH149oqj0janrAEe9q6Yi/V0cnmInSD1rn7tyJfRyDiivchOgbH9IsaTKcEbhdPTRa3R4oVgo71TJ6iNXflq2VkDArK+6b3UkqUfTX85jJZO5o6Nod7b9pGUo1xHaxP5rBSQpaEmyyCRaeqC1XYXR5oLVjlsTf5LieNw3YOEQEoniczbX97jtCmcopG416gL2srDML6E9THXOop/lrm3HaJ4TAb3RyzQ9KlUfKSTuoc71UPu8ju0ob9plqerbzOixbBGLw+My2raKlyPpHwQ0JvaXQHuDVnGQ8A0Y6lEztPteRwaIkUzZLoagyUqSHBEwbd0qdp7yy5694c9d14Jkut8BIUuNg7K61ebFKmJgMp5OgnV8rNwmaHKUszeMIBUitIy5fhwCeyQ34ZTxdIUEipDWdzc+yHEIhc6zuvkwSjCZbGple3ULTjgaCpKWDcDjsIBSZt/tzMMZQiUFkD7kTIVgXxYPypYuaoU1AbYMED4izux8gVSS555O7H0mXV9tnq1MtDHFJCVuR/KD4bGvv4gtyca7JpLebG2ZEmybScYkkVvUP1x4BMvaj/ZxhIVtR0Z77zCZda0fcI7MS3rsQohEFFS9wTzlDGU7viF+j95DuDQ45ut5NyYc3j3DB3Bvz1DgmY6/DQBlieWZdIH+1X/evdEoG+wQmrCPIysg1gZRob2bk7c9nf46Gc7IJ/9Z/7+F8Oc9Qm4auqJo4B1v+js0kqC6gZXozD+UWjEbaL7QF+uAM7FGS9ipNjlt2dCf6f2CFwdhiD87QLAHe94sK8w/bs0X+f
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
