apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCbzZZdKwW8VLXWvPGn5g/kpDhlJ/7X1ovxD1OVvwTDYkZ1iJfDZW9Y4aDJPock3f1CZRiWYSIP3Jn0YhoJFxbvEns4dRavreZ6J5uYXirocPvBZ0BwgGARsGljr8O4lc/kiZF9PoSNUoltY0oWYM39fhUp7ECDb4db5RrIcpiBDATwnisQQqWjuoQ+AfaklKn+6h2QNjlmQRIPf6McKPS406LsgkD/sG6xC6aD0YiTd73+J5kaYSBFRXLmXpRnAgGK6+vnZadiePc28flGIoNsER3YMRyDVEn9T9nupDj0ZGnXdf5Ol4tM2pW/hYmIBveLkUBOW45vkIoETxxl2RIpBJPKjEJU9Sm3CWr9ixhuoNJRi9HFv3eBD2Rs5CButFzSlC+gbA9PdS2w32rgPesbA4wnLa4Y970TwD0Cz+DhdtJeWSW5o3RycG2lnFSAU8SttjCGIHR3RIJwkylHUwBVEiyB5f8V3w++kgD1FWPROsD0luZJUoqitu/R4KeY7XcUTWbIYh5Zxm7rDhKf5GTsLbP43FoRpsQPSaST509njUfu3HqkYFPY+PduRoaNGJsavp6yn24HrRP8qTvJIetgjPa56cZiRz7GpjmZebrdCl8JsVp9zysO1bD9IjwYAMEkBcWSUWbizbaoLD4RSmImMtXRHQamQjY6QCv6htD5NdSTBw5DqzoCh28BGIIp4/J3wddVZibhgscLNYQzmoqxPIvgxP0NPeMd0mu4R70b7bSCsdnN2zzp7vofOEzo6NuL0eabkfahQNgl4R+fLTP+npDfAwt/BUa6JRI4boOsKGUFI7i5yJwIKmvxFNVGN+8wtE8q0bcaW5nxK8nsUjzWPtbzomkd7hERvHa8/RSIxWXmzHgW4WSfRMPAynNZfCSIq705nOY2jQ7lpJIQcPdA6zf60XffS1eK+s1vSv/d4BTJHaGz70SFsMbW
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
