apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCgVkclALjA2UwYPjA2sEea/u2RVnJAPtrpcZnX7yAYwKBdRBM7bhu7MQmEqIN5nDl5G24LSO2A1MQxDThCV+n7Da0ZseiolcaTEDlKTGWvexQx3o0FaFLvLhW1T6OQGveAVm1fl8z0tXY3sSmjDYS0Ltyw+h0chhle4ZQp7ArmuqQ4PAtQGI+nfIITTZHgxrR2ryBiI8GTiHXQJtsRoIEmSdc2FBCHoNyGgCPY1YB8kz7u3UOoyBSxMGUfTsXQwCPQunY/z/H1AK5IBYYi/M+fEfqFZNZUI6bQQzrpthHF+3DmoaGnO5lAf6pBFWm1Gl5y2qBGfD7uWPEE2YsLNne/l+NghXMJE+NPZOBwJkesvcZNjb6eyrrbVJf1bgr8TFlIp6zqsZYWVlsuZh5JLEUs1UE332jl/mH1d6RNDWclHygpgsmDhG2N1jB04fORibyOCb13Ru/RKMIrmfs1N10CFLacqAH49hWsyIz3uttmAKdCOKGoU+xtQIuc7fJgUv9I7hcJsQ+SiMUthrqRkMLRO7sAALVBzYTzjrZ/mdoAY0iMCCaGrFkxAlEJ1uM6zH7ZBVnhVTDKSSp9qCiDgnopLGU56zW7c4rukhUjnBx87k5lUSx7qVMqOqThIhTCtb7TCVyzJpU9QhtJz2+8+ntg+f/8sUnNZKSVcYSav8bPp596h8dotRSxFU0QFXyC5/RKA6x/iHs+lcs8e6w8Q/pThE6swQOWxmcadVA8s/vPYkbPL8HDfLutA/HMCFb4pAS8FSr5GKRjSDqGjkGOQtKrnsy0dTAXgULUapaLPnaFJ+/m/dbj08IXa9lJc8Ty83ZaVPRKjBGiG6qetGtGkLCKB5W33V4PYlJTEHfB1N/rQ1iNDPmIB4/AUrf4WFclg5zHfqRCiUm3IRU3ZwlA4GowMC5JRVQxTnl/ftI2emf9uWN4a8e6kBx82FUa
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
