apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCDzW0JxPl12yVdGtZ+SQd+gRwkrtGD6iODPUz4yyqEi6Sid5kRwthFlfeFO6YcTh4oC48LHI78gteZIsOFkm5+Jq8i14OOaA+TZTEBveXBQ8vIFr7UMiOiWXFlrmbmCV8mCZ5S3MWz1OE0C0mQdjBtyLaK1GBkYCpr18x7cnrk7DFIsgqUCFlAQEMh12Zqq81dl2PB+tuS7/zLfN2Md5Lfi8M/I4aVV91ToJlS7byAi3cwtMqC/2fiOCeLFbkRwVGvC/clq3JGa8Pg5rypQababrNUC9biAXHuufNjZzPK0cfeFghILPOOQMC5Tmz98YJcH5rM+OMrhPIJiP6q/uw8NYv+hYt3edfaIc6vtLoGj4DpOuA5klssvI8EKtrlJTtk8I1xc4NMCY+2/Vuyws4XJKDUKH9Qcwls/zsoWMNqDCzLY8k6T+E39RDqPs29rSU5bTiwo9+JHencw+637GpfBkaUTF+1xImhZdrNBaMukTkyPzdZmGr2QQhR1wfnG/YyDaCOhLQxJ9C90/W7T5JM4QMHi4yMPvrMTUO/gQz5+CphiBPdwjJ1V6/hg8CNQB183tJRAyvE1O1rxv0rDzR/vFxgbF0NcMcHtOXY0quIFiL05tCDBF44jqJtvO0PdRZajDjFbuXB+lJyfPFTiXTMv3A1xNDwBEVNUMq+NU6xeFb1skuM5ike5Ccrvw7rJIL+gq/TRFx6Zgnu+OR7yqQAPqzg0YUa+CZxO5WVgIijg3g9EmaZ+uFEahvDn6J2AX/r0Magtiu/bGaBCjHV+FrWtGNzB+fIqO4+6zsGYZELMxi80nOLDtns21kteOeahUEwqZaOTQtnE1YLPOCSZPI19IV+BpiH/OcP7bvWz1Dq/AH2fhZ92colNTfoxM+bWCTbL9AbPD4V4GvmrXgerlDwVbtvVhsfnY3ETXz8aO8zw5bYJ3w6YzRHIu4I
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
