apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgB0IrjLxylS2CKEDhtubsmEHLI7N6dbD71rNlWDFwBsgzeLC2EoBlHN+7cLDdlszqkBhjFKyNUTKuzPXRpJxgj0uqttmQ0L+JZLQmeZoFof7xZJ1/go1xGtfW63ROCw1PN+cNvQj7U2LBwYMqY0h6eydCuxpi+ix1jLlQnXjI3KbrBBetThCvs7+fMvXhP1q6EQAlT9zIY9r1PGGPpqVbYKGYzrsQG9Ok2XquijVfW+xKn4iVoNi5cY5et+1UelMgPxUa4qj6KWSg03oe+zXg+u8PXE3+78P/ckjN/DAdkDnNSfxNweeq2rx5N0qECdu2pgh7OikuYjPIUj1sqkYsFviqzBbmjlCiU4OkD+qZghiGwpghADfe5xr0Slhe0aqTnukh7zHWi5nv797RvimtfaJUNlhQHNVZV2B98PXdH4gE3ttgrfBBa/ZGk1OBs0Utn/s/ro3/0XXFf8zDKv5l22ltBTiU/lklpMsOaOhQL8tQr13UYsjf9OA0l2zEqLB+9PGxGfe/OV/FRy1JDnzr75nvqxg8lzAZO8NdmR/yViPkq1mArsTNresz7z/BeXI22wZRcxdY0IYCfQ5Dv1DmCd1GglqbxLogH+spHC7tiLH51nUMivW0LrcTnfJpcCZZ9si8uAwaZ6Nt6NLr0eS4koUYbvfxMH76ozqPoq/Xey/5rAcTNjzBokXMQmCjPaop/ZZSwTaYgmcpz+nDIOn0LXYNZG4dkfZHUyBH+V3GieZfwoN3wJxt70
    username: AgAfXeOmyrQsMf/NWsSz08+0h8nARflLndHvK+E59kp5GOt8xP7RinxWYora0yARHkEgQ8w8VwyTcOUfT3MOFo3QampxFmaYBTTFcJcwZ7Jw+QZZIASK2m1L4AnOrnj5pI8BFW20d/zb/KK9IFli9IFGEhWVoJgd6P33TYokbEUlqXkcqV87R3SFvhhOi5H5ZS6Rj0KJ63sQDIwoyfH2S0Jdh9Jgjl+aGnvjMv2hVYxo5FwVLl/hPrBZQqHtOcuPRTrN9h4UaJEp5dwfIUm5FijK9qR/jBEVHCncjA8yIKkEot5yAxUY8w98qiagmeL7kqeSdYJpKRDjRx3/mnOfGP51OmjDYSPI/IrzHILbxJ2Mg5OpHMnRwC/EdOLVZz3iyChxJDtq5SZScju1YeB2oTNwAXtapRMZGl5UpfNv2eoxjAkaAiWv6O1duy4jlrXnd7J9ARWnMw2/YjnDrmQMPYGVZ7ccg5/IePDFMnqDlGGPfscu0TfK9NmKRDTQtcKKqtSYx1cfSYzSCvGNSkgBMfb5emMYBrL1qYrPmKwCNfISSYrLSdQ3iInfWe4UiFcP9ifOJYQoOYodhwiYmmdEumzxlInDsK8xAwz7gOZSZxKl9vaNxitmplOo4GhLklJxVEzdvOnoPL4ejcgfT/8m3iIhR336H9RERujRRUdWV4uGC2r+eQLNvht8xSdNS68m9VQrV2MSQC4=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
