apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgA0PNbcMLw9sUQ2yYTLcrKNJZZNMKwoNF86cSW/L+S7j4go/oPmcEP81eXuFHYJyQcMZUcIues5IruBbP5N2cGswAvNeHYZDHU18u+/IIBy/NT2s+9fIRK8fgtannFpDqPjEYor0uOh52VgJ+xikjtQhKrniXhLCMRkqceDxUgqc0IGXl4aZB8JD6PifyjWpOeGK77vOEWEIEmzq+sTbBT45ntUG1K7SYZPEX2BpeOd3M/j3yu0bcnJSB+W/ntA5FaS9TLEN5np+u7sw82egrSJB8mukM6G11sVHoyZdxs6OPE/IP/3+EqVLZKlQs1xDTsB8DImtmIX7nO2Erw5p7I1lyRR1uXnZ2Tho3rA4UDp8aTzkg1JYSN9TitGpFfdOUEaIEMlWTV/U922Ud74Ujtzoo41l4FhtDFXNSN7+nFeWlx6TaTtnpdWyZtwVVl8yGZq7x/aBOALn3pUhACMQmplkJoXPGshAPA4Jr0I90HDAfgP45LR3TGBppEaCuQADgVpkA2io2jS7f7YoWFAk+KzohOsrR6eIsjBz4QHq7AU9L0NpXGWA7WQxzk3OOEovq4jxrj0teVkT//PMakaNd1nQHA9WT5EtxMzPk6KTV6QCCtTTVulqv/uX110XhLoFOjX7mnR5Hy/Eb2L2r1q1hE1sW7vlHLsvtLWkCTsDGDkJnvWR8Drq50ajJ9lGyaZ0dw7JBg/GIVe+jdirn5fnPZumg92Wyk1KCyQAGMUa1SOAxMdtXcXnyCx
    username: AgBWhr9CjTZvxF33kctFSVjzQSAOlBtsuRxohzvBgCT2GQzqhWrl/DMogg4ybcwUKLSEtOIOGH4Nfbl72cnT+rfnfzGD1djCb8qOm5yVeVHyCMLK0/ZtIGTGkYtTnOcAh1Ju1V0O/UcUZdi+5/d+9HKiaF7K4NBYuDgVcGCMWewd3aFRkfdt1ig4GAxDTOED5Qe7ZBV2Vqg/yj751qJoF/lJppJAJBORaLvccs+Lm0e0V3KsQ8wUYOos1Q1GB+5On2VmSCrE4hr+sgBJlj3LgDbd7Ux/VHEcJ88Z10tMQr2mZg8Yc4ZT9XG6AjIW4wj4vdxnHYPnkkrZnLiGfBxTUDQ5v32UUj0qw93qb/BlEuOz3AH1zcfmrfgA/BheYUp9Mwdzqf7PVhBsPQRtXRFRIboQ7uuxueHxQPex9Lm2UBgIQeeh2Gf2TUHw8pAwkQy4DSvG8NiWJVbzoXNpTf7DJ/DB8pohta1kVYkEQpw9PUWsV4SJlsCtMb+lUoHq4LBrazy7aXahuvQ7c9LwP9W5LMRnoTh8NqOKzpLfbLEQpXsxd83FhaHnWN7HP0BisIN5dKnTCaXOjCAaRCZ/b2wvjdfTSp4MxBvPzybP0Oa+LN4mkX5GXhtRb/YUdl8npSZZZC1n0gbueUmIODLBHsMJ+EKDNrtG8L8dLXs6DTQcfUc98Q8X8GV/C4VJe9otFr/kaJ21QkE5TF4=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
