apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAnPX+WZFs+/HKnxgiRaCRsmNSk7dLffYhW2m3JF3k2xFhVdnsvtCSAoF9FEgS3VnhgfQZMgZFr70QEdhp035hqO04+/lOtAifreUZ+UdM87283YjZErE/A/m5uOUftn74iDU/KEpisJZr7KguzPa5Jj64mFzD40wipPMj+IYTmh/ssIx+cNry83YTu8s1L1h0UYHEu/En94hoUkQ77otBEnnWpXIvNZWKmmcSBIqRGEPp+KC8RRAwLighSLfo2+qKJC6/n34k/3g+sqc2XsPeocqiwrwUi9/bJGrk7BMAhIAxtPKTZFPCPfCmqEj7iFAGwVS8rJ4RLCiDWLX9tTtJ1xzkwl8cpLYqsXFDaVized5zO47lT2JoGZvVpKNVGakuf2Cc1I+pv33/QLwjFWIOMFTBaMQcCjF3dPocSL0De4iiMvhWSzq6FM0yh+rpKBcpRrmms4i7hWU2L+cGsYF0jIvwmsqDIb5kUo7MPpfLaJ7RvMCePgmjh7rclfqO5HcyDbB6F//IlQGBo7aIm5RFNY7U1Jnp1cYLVqt1yerZalMQUlNJFfq605R1a5+seR/W5OnW3xODYjp/UAEY10U6WT/oH+ycoAUqV7welL/yMkIrEyRxtl94aKQxD/a3s9CWid2YIFGEUrJ5AmKXkFZ3spncsCffu7Ha6ct7A3qHpEtgvSPWvHeUA8uq3ZGtJHGRw5EEyFDB1LrFoluLNGvvPUxWhdvx/vSBZx8orT4bAQVyheZHw0KvO
    username: AgBQ8lVbmCwVi5skIRrfeLFwnRVsmh4nyhWHrfw0k7Dnj1KuQyqwOO2N/lTztOI4+cQQ12QUsaEBfQuiX7RLzpdP+5zldPlCogAkCSp3LeBsUJSyC3QV4Mg18+CgJ0WwFmRf5GwhuEBDrW6rm7jTNQuiuFQVeT+2gG8zj2RemfVrT+UcDR5zcytsymNIAHqAaR3l9iYCb1d/OtqRHSWrU2EHlxYCK65tPjX86MdRVTB5/jPwfaH1BqDWz4UU+qI43/VHP1ZX+o+VGc4GUYLNNRwMpESRD/vBqb8RM3o/UZsF5bcga+a3iTqaNijLx23m/RouwDm7pW74J1x/SPi5Ts+tJv6X+PHg15frBPzLn+e+JxrPPnjzt6j6v6rtszOjBAI/STFC8lKkY7RNQGW3q43SMmdckamg2TtbAUrpKuNlK6rTUB0hWZFBzBhbfXWHiEjWtHV9cXFKgV1wuD9CL47lYTVC0+vpRSSIl22dsFdFU0EqNHN62yAYTVhTaFsiDIOaKSfBDEKu71HhCkyL8HI+8kdJauk+2OkIpAF9vV3pgDu+XRG+O1HVk6a4noDsilnQwEAgE4MqcNA0QmEMsoekJbgWgWbrfJ1NJci5RWZpWdM4WG/rD8OrikNFrHt5fML9fjUzTYFazhk7ONeqkVx/hlVpgubDARWz1ikCv/boUa7WtFe4uD/0IJAcJ9Vfgupp8H/vTVQ=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
