apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCM+ty6ZbJtOz/uqm9XcAc9RUfUow427kw8FXuFdw7sShnfKqzow5KjOEhPOrCFvPiQ+VxcFmz0RYzduS8XzXY29jYAD52FpXSa5/HPJkx3zjaBq8iW7WRU6iHjqJde+5cMvagEWV/ZVAw1LiZTSFh5lyC/I8O63YURdIXP/2oTQRGSEO52RZUlgBCg4DE/Y0qoBNJ9pNGzhvxNvlYR/Gj9WMK6zoc2eecwOdVBMeI8t7kD2OpOmthGYepowRIAT8eB8Snp+6Cf8EqNvD0HkJiKjRxsqcVQBPheNo3Y85ajLHy0yMyFQm1AosiPy68YdPh0xVwNa5JQaeXmdhYK1fz9LQcf7moY6LnWBdCyLZdLq0AJi38iAnbkcSPTBMfzhmMzMt6C6wwaAESgBUxG+9J8yhXtycaGLWubowCpgG7KpXwXv7pH6Wlq1YyK5ag8ViEuxzDLjyYg5+4/2GqLAvS4y16i81PV3c4eW7TxpKxNRu7ntVPvNSw5mvh2NKgid8/2pewxtnlgCvUlPH542Fr9h5VyPbo76Un+R5GTpoBCNY8m0Sa6PJRzopefBLH3Ns1DLpj4s61qmfp8+4NjIyszEIOy7BiPiI0BWCjY2DQ50smyHVXk0hzHBROqhjN5YxYBjtV68H3tc0jzUCH0d1Q19U2iYGm3zq+ZfnhdW/NnIrFH/PMve7BGbgazLN4lXzhr1hJSqrMSMF+muoY9V9P90Bh6kGqSaNikkIg9d/9ct5OcN6DEo9jW
    username: AgAbyK3SGPULKL7uv4mhZDozlJaGzq6ujvKx+Zdr0cFhh8snw3xSxcSweTxvYRsbVrA1KkEb0/v8xwU8ce4NlIRbGZyNw/7AhIgOh+Q9Xr98aBF8H5ZTMnUSiS6UVB93u+UMnycEftofjwMRp5AffvSqRASH0cUk+geWpaOO9XzGgSQw+ws9WdqxhtuTe8vIm83mcfRPXXRYOZD6BD6ak7yYxrz5DD18GezQlnglXSGyNnqMkDu7izgyxQADrd6e5dJ/iJvmRMbIxto4i0IfCYjXvxecS7mfdneT6i+oXPP3MGB1Z7lCE1Kae8mtYWmFeQqMqLsxXHcYtcLXekAd1Qgl78enr3NDxBK0lxaDkGX64y6MatohbqyvkRz+UAJg6KWQSYoffc8DL/kiNaRahaKxATeDwNOahQcWHeEPqorA/thYsESzY76qBHxRQ7HaSLCGwLfPzp5mJ/LDihDqvYMcC4eKedSoFePrit5uS4fky0ThAxw5seAyd9x3t9CLbi+zrej9AFXYg8x2ah5AnmRA4KXz7L3n0IPKLhXH5CijuIrlGE42zdHxJOKQtwOHtt965Y8sx29aWcnhqHc2OLnN7fu9w5c+/pPrp0uhrxScFTHNMOWSvyipXk5i2C9WWgbnZ9oLP7PmCT57hI0wCJkiIW6vNXenkEU0FzWEYXDBNOUvGEOGCijBiWv+FDPnF0yab7l7IsU=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
