apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgC5ou/bt0OgFQIHy+/GhisSQ1+yZ/wFd3SetHWOGThJ9FpUTbVlbumt/xLFcs3aZ0R2xYQqEczfRf6MbjTBbZLUF/haJjlIII5aKHgyZhjvE5MCK1kf268cRJNclD5imIt31nKOxV5Kt4VOfhNdA9aWTa+w6YcCN/c1c2wddzCJzW3L5dPTUoAxELTNMmqttfYh+MSny3lhqS0TXwA3cquFWJachLPIVWofZhoADMChltRmWR6Qs1zZzyy2NdKqn0pWg2T+n9iF6dx1MRcSybEDYE2h1Qk0e5ZqO7bsO7Orr7zinyNi5jNYDnEDb+hLYcSug+vLoxkOh4lTJNn03fxLehr9ZSEKScsJ6ZBr0CsTMEtUpFbesAE/ezPxG3Gfn6ab2MLZ3Ry43XnkTgTrixQNveuLy1V3sR9SvDx7ChGI7xqqYIPBnmAxLi+vbH8Bk8DrpBRh5P54IQfh8tucO3NoDxV6JnvkA3uZ35Q7oaoNSFMWhf111rN0ybUow3jN1m8h74oQ+KXCjqwCrvx463HCm0aa3p57E3BQdTrgwnkoyHO0B7EvZxQF7EHP+iNFAN4FrfPbOar4VAyk9kFoDpSnvNm/OAv+ZLY/d2LqxMTD9B3Sm1YqQ9iSlC1gWe+ieHcdbMTTlnqKYzEKWQ00Y12QZoJ9eFkjr7EmIHAqIYxNAwJvG7f2PlBdTd2c40Ecsd/NQvPa6kXHv1O6RAxUMJA6HTaklUv/jJY3/46ApzyH8q4HItorSVxB
    username: AgC6tyqKQft4ujW2O4YxL9AxlKothgH9iEDNVgnjhUBpUJuJ3PcPVE6FZfXeyy5xyLq8FhJ1N+gRdT9F35mEStXlHMRcKdiX0W/bJL2TOY0lixHZ7wRcfzDNSWEfE8m+6L9e7jfiAVsv8zYs1Zrv2WrhA2g5IDCB65AP8bEjj+59D0qHQOmyWXfrbPCwsJD7IH9kNmElGsHnHYQ2c3Oibc4/5xwp7yYCIumHX8mHx3njuRJj790cDnn7rl4yjQ1FrhjVfrsEJYYb8y+2YB2TtfsPubWt5JYaGfNk3OFTKEzgCGSKClyukO9TSXLiYuuUFt0vZQbutwVlbIQQFnmT04FvFqRqZ1rEhj02//s7E/A9zBMArYFURjF3d9ddQmkuk6lFLOCSJn5Blc3SokJgugePv8UUsLPZT13v33kGsdn40VtSxOpHyBbxyi1KzOejB+Bvh/lZBgOvO2p79/OGxKw0Pur13wJSJ8FuwzSKrRkXLMQl7STvaADp63NlC5NqF70Exo9cidkYv7/WRIsuuBOOD5OuQxYJr+yKB2QKNJwZqfxe99VlBlcnRSNPVJkCSGuEDF42NhC4liOU1f556XJOGYmeXOFOWcolsU7ygcwFH6GhePSbdLhItrgmGKRInCKS9w7Z+8Tk0KgXXPZSIfgSfPvw1fZKutazLt1Tiqd3IYYk0spX1P9TYQCe/yIa/ZW393/ms/0=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
