apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBdm7DBw5zGQgzte/ptHTAo8deW7Psevjj/27gci2TFWnjbQOxxGlIWpfYYrtkLTr2R+3h5wBdCb1lrpRBTy+LuoWSuwMX2U9nc9kKBP5B/oGqppwrn8WqDxo1WhQNVDVUlDoCuOAJCueJmY11GXv6mLJxLKfwyoB3NTB1fPsXEgan7aPPzFknLfhtBLchAXJ2ut5XJVchbf8PQVie4Cu1ijb93Uq3zeeVJC/A4ddqm7ZNoQ+qOUCEIKL+6yLG9XnlH0N1OIGBCzRGK7Lbq+t3vo+GqOoVW1XIfhffyjS0FpvOUnnDBB89O+IE3rjKCK3vHf68nlPp9LBuXppFEkrZPrpvoeyl0TdhqT7qQ9kn18z68NleJ/Z2Tj29aLbSgXvOfQXpdtkk6r8SipZCPDn9ANos0hqQ2uxNOzir6kW8aqVQiNbDsf13WEaApGZl+kGrvbjf2sadM+PglTZKnGFj2sywjW4tvKdxzybDfUeiWxIBNx/MX8EZlmLYTAS2RH7tNa1yQYBAJwhHiGkcBag6/L8pTJ3pryYBlhTghARh/Odz/6yr0n8gNzeWQK5B0OsysbwQgswLFJRzhMvNjuqnwSRlTWkgeoecL5YHGsaNBrl2EAeY7keEmb1z9wqyjJzWqYZQSYhtmnHQpKewjS3ln4KZ/VwFMDZQ7fmii1lgfNSgXmELkiYbBq7P4iGfctf5aU0puOOYCJ1nWHLqJV1wUaTdknW9IiELd5GRoM9nistKqnQLUneFN
    username: AgCItayUaYE/IFfH9p+EoFQmEEhtzdy4tE8rEUCEM1opENXPGcJ93zSpXqYil0Y0imWlcyrwksKgvRc/ScvB/kbP9wqyyul5hD3O4HAG1wL18gDXI5gdSOup0BqkN5VE1Y4E5SufKQzkVAfWoNdQdrzN6DJGSqu6C8Nb+B6Ap54MlZgBf/b3bojD6A1fEzM2vjO650mcmBzVGEgyTJFwu2NoEv9KLbL1lwocG04bt5CuSPJS8Gj0/CKlqULU+g3NHcT8sF4QOF9ySIDUp0O646WFNXiIKu5sWwq65Sb9Hq3qRe5Hi1wbcIxo02/LmYtvg0dLIvrkSDMN7Y0CHwWr9bRgxSvHULnY9VK4H3oWuYJnVFrlpBeFEOv6ci+F4MNpykKCA0wtnwJC4t3jnKyBlv/PYV0HG5+T9utQVMqQ69dg/5mcBp/0vtQT3LNyPWq8LwCAFIokOhr7M1rVxK9X3l2t0Nbq0oNNbZztc3vDwUrxj4NU4qPh5/yDrV8tHNww6LRyWJ13x3sGVEWMXIjmKjP2fAiCZDA3GgI0gjU/oVrWI+5FGAmQuiHQfO7n1SoavB0ynmJN6eS0vC+RiWmsd2naFv4atZ86j7XmG705kBKoOSJ1cdj6Xm2NLWJ+Iu1mq5bJFqBEpQ8WruYFjrCRSlyPJkaQh8XttkDxak27U851rs7sn0BuEZoF+Fs6+jvYt2uVZDOuaE8=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
