apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBXSxud0VzmEvM1dfrUquLjlKQCwuKfbHodIxbZUxB1ctDPGqte+I+5+4hf4CGUCNWlLs4QN9f31S6fYGM1kg96JA6qMWZPofXjrnhUzNhyspx2MB59LQU5Xd85/PagNFfNMiFEYKD51v6K/wOWmJfiChLyACprgY8KPf9nqLTaDxK/ZTmw3NG2Pbjse/yGFP7JsNz6AsX/Gt3CP+F2sEHFTltyJXwNyedihXwU9CCmbGvEih24sr/i6bBytIvnucfqPNjg5Q3DkZDxxPV1zGV8gz7U3tC0WQnMeB2IIm0RcjyB+FAJ7pQlf0Gs8qcqwBlmbC8h+dSYJhfhNWEp8clELcikau7RvUNKQKICdwv9mcLbjee5Ym2wZHF9nNEXaHmynHvm8v8m2IQXGUqaXBpKpu4Lc57MWvUI4JFuxXUXW9/ms1bHXOKSpOkHffTcKa3OdfSPi++C/in8K2zh2pNyZM4iCms7+eYZKQq/zuiBgIxzriWXm1XMkiBLrT/kbzmVrKvQF0goDxJFXJR4pnYfjHo2xvSabpg8iBKRVoFyeK3rVoAqezXqNBRokG20AYRl/fE1HoyfujUIyj6jawvDbWa9NCDVFy1P0gzRlsrGYeHXomWYF1H7vR14zOJIUBF2ohZgETusD2R9rRJnuzCuEj+8Cr+thqAox87MfEhkUf6szvTHPkBsHXLE2LRs7v18279o8FiKU6+JoC/Gw8vbouIxeqvhzpiHa2ydnvP7CzfcO2NfNlzb
    username: AgCEeB70Kle55HIgK7boN67MkW/8c50X2LqzmHttOPM3zqAXg1+g2Dm/ktLfQ8FmDyetBrNQW8ScDhztUFeRreWzi+9ohrcU709H0AzVV4oUKhfdhUyBSIRsFb68lONYhTtMg3cmQIBYc3LbJi0ydzq3K936Qlsrlc7xH618LZIOak7nnHkW9tkRVf5sb+l9nFn4eoTFAOlq0iZhRtgXFuD7vWd2bS2I/PSqS3QTnWLbdp10tW8Q7wuHu0kWHr2ME1x2AAk3Pqfv6qJr8RWacuGM6JJh7Fuz4jassoIrSckwuciMlbWTUcup6QasxqP2YS1+ar9cjeIyS22B3Eo9tjwF+aWy6qU86epDTaHWDxHcQUpOH4sPgv2o/IBnOgjjKZLJOVNFbK6q5wOHZwq9xASquJLadzM9gcaAM8ii8Q6NuruIxtKmHlYWKGqQbh0rPHbw320im/u3/AsjcPTVUbnuADknyLALR6TvS4uBzy00nS4e+1SX9uV+eeZZMDoz0RRwDKGS2lDlBrtRCg7anFC8NJIOKqxeVPFMS1F5RdQwj3G3RWHBSAzYRjunMIDdP7kKB6rsD6YXCOhShoRCfUamCvyQW6ax936dbXdYANagDTcQrgmWwFOPVST7lyaYq+mQAl6KqfYQXz1J0CorTHGLhu0I2Ve/aJRlypdNh/Q3ksXgE9KexwzgZwDApY1Bl94R2nLrX3U=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
