apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgDTaNYkTCyVgv65FBQYjhFIUYT5mjsAYDZiwlaDBuWJCNIISwQG/gWrH3uViLkvVys/k+tFEnyY14LZ3DoRFi+B9J8QJtqBXdotcabfmuI2qgs7LQ6wwHE54zChl1BVVopgSnCLKCz+wymqUVYcCoKrxdzBpJkyLTFAxeuOuW9FKJh80maT55zC0CAjinUUYO7YKeHraQhblT3IGPpD+rgSLPrVirw+NfxOIssXqkIwZvUwWDWKydvXU4hLwwa0HCUAabiNi6IMjx2iJOkf8ANJldLhU5Bmhzlk3QfG3iTvkp1qiUVl9Wb1UzbmujgdiAsuL3NiIEMz7m4MFSuLYhXgaiNqyxfANWVbwLZifGmO2uSKKjtvZt7s0R0bP/dPBAfFkuxm3Jj6HHMXoYVw1MIeyhCCY9fANvJvlRtZKtVWdZHIarAVASY/Y/IbJeEPxPATRnEjic6pK0UahnoEctNvU2HxXevyymnNJmHdBTHCDHp6D8x0X282acx/3BgI5PPa/qJvQ7PsifoFD39QHAdQ7T9gVpn/0vclbW+gTWM31XSARubqDQ9ntoPf/Fk6Fcbe7WTm80DI+jsIYsjTJsRniZbSXLLGLB8SiFi4twcIbSYoA7VPpz+z2kCqYq5Sx/61lnw9VtQTNl/gjHoSZSXkQCRn7YqUBWiIPTG2go4+JF6VxVJqgaqnai3zI/NfAIWOoSWjs+NZKrVTDg2iuQNcEiK/FzMbovXbX+rJ1AmVxy1IVKi6MxQr
    username: AgDMby9IGiQrcgnWvrTtPukFV1yh/mejcFsLN9ZpctT1cl/m7I/Mvhpay1I+LamC+FTizpxunk9VBBYNNLGWxoFa+Cs6NICsEFpt2nRTlC44YASmJ1M7aZPb2ylE9ca4QCsTRc9fpzYQxB8qNpXkK6hg+OhxxK5g/aY7MVUhvyy6hUFS4NMX3fevNwbfitSt7sIegha9rjWiDIAXTFcLooc9EMwfy3/RYMNaGcfnzaVCgy2DWfV3piwjiKmBfBFaVaWXF1BBOdlQkGedQDLvaZ/T2SPwEKHQ744HnzWU7xYmlhV9wGus+RLAgCjXIBfw3KQgr/KrMXKZTKEFrV7dkG7c3YHELcQTqIvcC5bFga88ierx1JEZ6Se0bBjYLoCxdLcSpSw8BzH0YkZctSlzb2s0r4LB93KY+fbpcqAuYfWOzkw2y0kY+DgjL9LY5T4czqpJQNI5DZFIYN6yO+ck+hUqUMhku0gx/ZJN6XMuvLlfwxc2Fl4ASQvIs82oAcUKL0Lwni0XZbww5ZkOiJ4gwTcBcRouwInvI22SnEM7aMyY0fa5jLPSpSqHeo7EU86yan7rzhPmfJICLv044B7iS1p9HLJjHwkoKj2e9LCHW2KaNTlsncAoxuOLp5U1zhZHnAk6sQ27Cy+5xk975cgRQj/ArdUwQbzuPM6uE7RMhnCizHyKyqBqtocerpSZjt3TpZGeCeQoRPA=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
