apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgC6+jdY8kZiF75rMejLyT6u7O9NIYnqqVJlXxMWNbjr4l7t2SeYkxxngnZTVRjCABfYyinJUehrOTu21VihOuCxrwRQ3ypkJSgH6b7c7ttJoCFY1iGgtJi5HFfTC4r1Dmxy/B3vH+Runnk16NWIB2CPPPpmfNZeqWXEGLYSmqJAhA9rVSu6nCi8jfNNHY2yMKM4L3ATYBXiWdqk/hajoS53uKUXvIRMOVZBHRi6vEAY26a1VQMFvfI/M58F8GQLmFUr66KUcfo4513Vsc52/pWkbzA9DE6ZC70/M4cqHo2hQpMkBbUgHLz+JOTgM4UZMTA++3nQu9jJLUk4SerVb7RZz2HoX4QJ2q3Kp6oV2fKL0W12nnkDmXgkyIvxkE5kOL4PJV9CvTPYfJeSET2NHuPjStNdBlFexVlKJPawDOMy0n5yykKE7XggT0Oz2yRgAodXhn5CKAmZeZzNmaVeWzPFHw4tu/mpldIhEChWi7Ay6na3mJucQmRJDdTdzLtpbXPQFmKbvRAF6BypsKGWb7YnyaNAIC/xvPIEikF3qtAMe9e/yx0Yirb6TH/nLcg0HzcdKWHsuERNtdFN+pOX4AiEbEPMsoqXHVaHlkkBSYyU7YYlUuEP4UHgyuuf5PlHqih7/Yv6mAd9niPSD352LlyE+XpLDEGh32OOxZ83kcujDzrG1AZ5KESG8xh1JbqcCfF90EfySARg9fDFCLQzj19G05ArsltY5n7XogRmUXU57GMMCs17Wijc
    username: AgC0rgAKxy38vemgPlpYY4SYASQhE/RIf8ilW8gdPEDyF+A1m5AK84W9B6aw4MSeYA0LCGG+JISNzHNZGJIavGncuoOtMjMP7HDxYUW2X6rKVmYr1P0Wo1Zup4NdW2T9fSwZbqpnDSrFLQ9RrZ5WWnoqsePzDksCB6k27Pm27pH4gVNIkLs5VU1IlT6XpiPY3GXgNZq4MGuolc/YuEUt5q51RaxU93ZWHSuvkuCw5Ki8gpbW03s23vzGqR8ooELfeWY+Rxo33Kj0NL2/+xr0lcpoWzHo4nf8m0KbP4rncRw4xYV6jcYtKnUp2PEdoBGe3v7K6VIth2OofqfPw2VlSj9AhfkoliwIEAkTOBT7KmYflgZ+lLjRRCuxdGmUjFvv18DFc6ZMGfbZM525KKTMZNtUmI3cF/ou1bZpahfQl+M7kNL0Lczau031ab1jf26zKEg1phFAXDWHX7nKsyfRk/c6yFuzxNMeKe0tD8Bk6270FPQiTPqPO1rfwLB9+jOyRa7VYgjbk2zMHw0aloR3S3UMjl3gLyfc3PT/RurMHTLV1w3p7fuGrmOH2uapzXo+VaySP6i/4lbOMU1LAl4BRut3tgBiMxKy3QodkTD3vMu3ePyQ/iKSm/24ZaEbGbEJvXL4ZpSOg7L++zYGgn/ZFx3E0uaraEh127HejbsZEK/Uc/hzkoE3XSun0ycS83SGaEcr5oDqBhY=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
