apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgC4z8eYhiLBlQ8keYHz5ykP6LF7WgOmuMUWI+ZoTm0pmyllnYXnyCSJ01N44S5a0Gh9d8reZgIbTDCZWzUX0bWM+9cqq57tYskxjrGJULuScUo6ht2MJIPrhMTPEDX0To99q9wIJLeo2xKQgC7yE6da8NzaqomhibFRntsJf59tV+J2UXhJLyKMlsRnNpdhO7UgoeJK+KaMOTrbJtxDcr4z6g2YOgAc44u07dvjj0fNbXouwy00KDVv8bZSIjZyqBqYfkklaIeYOVpRrMLNYiaPO/gCsQjxZZX6jaD54Wiw+YngbkwE5xJ592l/nr+lT7M3atCEU7ruDzC93ZZLbPE7/ueZHMXwlm+08vApAFJQYSyAHOkHeY2hrvWJ+B4LFA6FySef70aBWb26m3MLtOcsYiYKsv9espW8FCsK15HZ2Fx7ms/pv6L8Ce3uPaEhRFfciTQFrVX0pKAH5D+Qjv6NIYLdw1L/MzieVkxA+QaqDce8UnVta7FJgRFj8lVJoSa27NIPtWKnf1eItpX+ywgZlLG+4kYftEuDrepD6bXlmuOA4PteCtmmILI6m0mqMmTN1qMO3oSCFWQAfJBMJdZOYIdOkxVF8SdFGH/RLZiRcH4lISpBz8NCGs9MyDzYqqB+rPDpVUAEyXVcHhLVQFr/a1cl8+OlRXvJ70c9G93G51Ui4s+awV79ONFohmH7ABqN6gOPDvOgcTscpMCYV2L3FOnJ+63JU0+onGJfdii8jyQasy4ofNbZ
    username: AgDHo6PMuQ6nt4xUN9IHhW9hYrEMjYiM1Jcv0DlVkdJLksd2f0FO6euMrGqqhR0uZ/WrT82eaSCtr87B1SK/OlrqfdijduweX8AGF2F3cfm0Hg8XCUs/lHJUS5LYylrkb0csrmbGDZJMBvCHISQxMAiTDvBLl7rZv6cNi30iAjbxWHkD6anLkpkpJNWIzBK2+/wRDMbkIoY2bMe8lSn07bF0cK0zgjtI0zA02K6ECVCnTAQWfK13s0nvhh6A/R1CfghfQcpCBxd97JS0OAdQLPPCLK5BLWxeKZIHTgkPuqXv8eToVZ5/Wb/Kxbv/nW2zfY1MCtPxUr+egcVEAyfEKkcFF3afyiDsYLHa/rKSRfV661D1/L9ICvKAvp5DfR9zRzgrhsjzNSzMuq5dw/o6nkUzELPRzN7ZLSS7Cmp2+0PEijLbNAfe7RluHBqAgQzpzQyOdmd05k5nei7H1QD0dovosUuvJcarCQjpjfqLfqP7S82QvXgtREuhJH2cD8/8G0xSbtiA0TU68hnCrMmo886GLn0vfHkbORfQgL4gx4NrGIsMye5wSL1rW9tjnlm46fqvDZwOfRFVMqD9uCtm4Uj2n2+y7sJHTG80QemttHvXMSuGxnQRcSyoGKJN4z20Nna4EunWsRyNIV9f0HS3u9mkPnbsCuHPb9imtsyuJah5sBSwSa1irjeHHjlCfl1HAf/k4h66iVo=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
