apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCM7HrLNT3eQ8UPIsIX1+augnImDiUYMj/gr6BgEA2WlF+m9DYphYrCPLitj9VH7YqKNwt0w8I+Sk1Gf/NbGf0ljG8PEyveoMSskxjDJNk9smj2Taf6SXPbUfntLGoqJARIRZQ+HJCOBN6XBxqJ5mPsyw4sD/Wb8xXoul4lfW8WDPXPyA2Fo1OJA5zTeI26WVnM8ezzOjm7lPWTRcSUIqwmm86Zm+UUTLrbibT5ao1muf1uYYwE+rPtx5qX5yv7+7MKxjhjpdZItRU312e91f59Q2EQcVg35JFz3PxgcStMQ+0fi6pcYGYxlSK4xGY414nR0SZ+eRS6itIiUhivH/anTPT6czWJPqfLh2FLVUaoj0X3+F7+Vc6dMgaUQZ0FoojcKuz1nKqSnTNaAd0K+md6s0P0Xo+ce+prU9uaNTW1TJKfa3VPrcrQwq2jKvjoRhfl/XuwpiXOLINFNKbIwk1rP93dtfcy5h9jiu8tIx/zZhWnwCw/eVDWwdv206Yy+3FwobUtKmSJbzO5grfXV+uco+eoLca2R53vCW6qAXX+f3X1/V2BMTnY8SDzzlprwnbLqrYFwTnf22YmnU6piAEaHm2AxMikemleLIFmtqeSiE4SSff2SYckbdmfFuPHCMpNzZutcQLh0L2CiI76Vs/dzwY4ps8WfXg3z+pt9vEQC8QU1Qja2jvuJ62bbpCKDViak1sA1rbRcILbiVqWdi6hKgs5YuZEhK16JAltoQ7kaUtz/IaUSed1
    username: AgCleT2wAXUXSBlUSEbfzzhXJ3PcCcsZeQ0r+nMeNO+5dD1tRHpHWDhfmxUoevULeUv9X6ubm3vrwnK6gZoKdtDET7WrRmXzWs6cpReY95PEBY6jApI1jLvuIGPDctYlPaZ5hOKZJpYveipaNLboBtBPfImhTXmp7f6EvuZ8JnfwBGh1Y2SRwqiIzsH1/M5uaCe9i3yOaZvpbnb73kWmKMVCWJ3sstQhHOOtJvUZCnrj3QxsjFvESdacf8qnWnEx92znNI3sdj6wKL2Wx4KAkNKhgSoDnJR1/9cvDSec7ywzZolzwg1QzuXyYeMM1EL1gvbfKiPerXlQCfvqqwED7YEEyPisbV+8OaJ/hh9vfjHdwiDWaQ1Mc7WanmX04l/+WbtdJOC2pXrZLBErQidw/4wrQbQ/lHA5w81iRJYz6fSGYh/hiXt1Um1NBiX/q7vP9ZWKU3R674w/sL/qgoXjKdoAwgvd7HM8bZlteY8ijSg0RnaJVJXYBJCGJxuSg8vdG6E3e7twrpOEUK1+wDG2vH6Rei+thhWe5bNp+4F0tZ6/vlQNVeyUfMmyEhQfy+ZRsAkR79jZr3SWGCQSH49VJLYI9mqBvRtQbD++SIH1n71gYi+O88o5SGowOK0Lka0cKG2UetlR+IhFjkM7FJB+lX3ZqN/NtiuctCwFR7oY0NpARpqszy4UOAZf65stqXCm27aZpJUHNWw=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
