apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgC0cW2ajj0BBZpMQAjmTBbncKhyPekjiQxtHgrgie9/vPqUKGSS5LvuLR6CJ0wj5+9nmluWKJAOiehupYVDJLcavaRuR+UnBW2MkW4wFwyefCISD0CZ3vHElZdL0gkezLL1pzz8rhOLbvSRN4UWj5r6g8vXMdaeaLpOm90/3dtZd4RRZ3wiDOgVds0gOWPQt1gV+yZr3/UTLaSsh5qfcCRrRtfZWjKKtG/J6EVj+V1h7RxhwyE19VtxHHsdfQzXL93P3aSKz5dQeAN1xKO/x+WF1CtoVnWkk8LAnoeliggO5R0IdwL4q+3QGyeP5sY9XPNczlHpBaGub1xf+qTjgsO22PcxFtJlh0dlhUUTPEz6ZCGyEeoyKJH2bH7pt2RGu3BPSeLL8/MKq3wKb7iFoQS+Bejx/QsFKYebXx8EVlmQ2TPK7QSXlVM8qjoMzWU/Gnn9MYBsPzShaQok/8iF8Ehgi8Y3MkUQ3odebFjhFsJKtR+vPuFYWpv2yOPT0MeUwDou9c8TRg+9QMoJt/XbYjvXFRv//36iPUu/0V+bEXoekZZDGQ67E284snvuxeZkvjiWrwotCyVSdeQiFIlt4O2TjaXyz3wjoUoYJ2CMklk4IdqmVfn4tN76bo2j9pcy2d9eauNhm0MkrL9XvbsKzDZfqgHZTRWbWBOZhFhQR9cJNmfjU2vXYrGriSnVeTUFMiOnIMhKhFaBnCeLZnLXJawQeV2kOKtW9a6NJJ/T4uagWf4nSWK44TVa
    username: AgBNLa/kx2ufgHXiutbnW2zrVjD/ODd12W16mgCID29gmeRmQxVN219gI5BLn4iUWow7oWX5zb6IzOp8VRh0SQq6GOHQnkBgC/CNZRguXyPipehamBhjPQmNKGnFkda6dyCQC0qpZRmgS41tMUk5IHc2HBYenrarU4Bs5nejw0NU5ms2o3CV0Scjr771bTyHwOb/gtu3bCS8XSFFNtxtzkblgOa2t9mbZtZPzNqwT09cgYG+3eBp6SU3y7L6r+Mw4R7HG3C3wWBQ2kPX+Au3BFaIsa1JK8u3VGPry9QCLCfMnzhPeBbnjGQxXENAwvDX1Zv4lSL8pCQkMi2QBuR/gwhmOFS4vQ6eO2YID381UkIY5WkPBGUINA6c1i5GOwTZTbjJpgjX79kUg7p2X0PApSvE2pQe148rXtH6xCeYHiNhbFVAOQyfg+cYmc3H3jSgCrV81T6PcLkjy/PI4x165NjvNQqt/061R0n2PoMF9xQ3mx1ICWQNffn+Y6bSB4YqjLCWuca5oOkB5ysjCWqKQkAF4/PUUGM/dNfrHZtvDjfeACnbGATDAQdS0FL0eBSzZsouVS+uOtmK1rA7oC/ZhrlZXXqoo3X/A/9VBiKrLB/bQx6dGnvc3BcYJdckeF/kRuyTl3+oc7zix2P0J0VNpmtQ+hh1gP37vX9azDrlZHir2Mj8171pnpcCTQDdYlbcKvMkfqzCAY8=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
