apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBl1/HYMMp+6tM6LDqsWq/Rc/L0WixctecJOlkIU8jzgDrgwjPIcU8vpDRTxwrVD0cQrOK/4vSLm6HRE0vhlSNkl4geFNqWlIzpT8N6xUzDbYugldpMKUojU5I2uSUSQeDJFxjx4LK+1wLMMxleHeHuQbOeRArWuXYP8vmlT5/dlZtdbTY2fHGJEbn5anyEE2zHWXB1jlCYnkYb+0LyUQV/I/yoXx3DsoOdxNh0cUXpyh5CnVIh1vpIG7Zf9czeZFs1vC/YoUvMk+ktpdlDrMMlya4A3CFRoC8WP3aMURzOLG5p1jvNsF4EZ+c73yAUtTco04OUcaruzhDAYkdc2mn3/RW0sRjw7oOQa+seRbndQE3AVELP4vB+qBKjNB4ixhss36D5NVuL3PxFq4I2SbObMccjXD9iYMHNjUE5w0YqxsSDbQtLAxV542BeTIezgR6/nsMEATf2phKGYzD9cHkTsKpRbd2f2hOnxU4p6Gq1uBvXJ4DmYiSvGYOp4vKvZ8f0VxLjghELYSTGz4vuRdsgt8RAxi/34b7jBQopchmbtfLwolIYTteJX6IvUIiUHp+ru6U7zie4s4B98cU4oPO4KMB3IAanfpOmd60Tczl9pSpZ3fkv5mgAEvGoVCIAAbv37pcH2M4wWJyFPxTYpCYRvHbcumcvXOjtReUD7cmz+ZzFa2drSp2Bhghmd5gTZU/YL50KaRXq8cqdl0MOLathGvr6I04ja4YkxlLWVBsTtDBk/6mfZzM5
    username: AgBHQlKjSWZ7xWr1K8dgTE4g7buvl4rZaCs4EX20WdgdIMvb3R+J33fCg7nvx7L6XQjApyyM2CmI6Kea/qoGqThdKknzvBAiM2gINjL69vrUAhwYzECAsh04V2l9UfuaGgMWcsnaOloPgkK9eEqzdU7O/t6d/DHvHDXMREhTn1r+HX9vd9wPVtyWbfnGfR7Ok/GyB5KKgXQ+ZE+3iIlUQQXK5AaaHHPgtkSNyXttzBj0ygnBAcuqp3+ELfoV3/7tSY4KJrWmcyEIV5VqVRckkPE+lDDTzc9Njvv7dkYU/u/Q+Zck445ohBCXHf6nXjpN6EUhkGyMwID3HfYCTd4bjdvTCK3MeePknrq3CQ2kqG5akOOcYXQDVBtuU8r/+QzD5oj7bdMMEMQdxA5wpUlGwXHMGkMqxzCEmeNx6ocrEsc1N+rQvUZuc38bRHH1S9bSpE2V29/1nk8AAG+ZW5sozkN+sUCClqdR9pCdpE0wkxinMtM11KFZ5kO6KZFl4G3PLh6Ar8MtBNZPRjMCujt7kD9SJA6nxI6sF6SStVXRQKfBYBmIvjUTGojjt4eOg5/tb5SQiXiYif2ljA0m6mhuIiwehOCrN8YFB1dO/FStSJLMY6+PkC5l4n+GUPkVGSELuaqZvHo7ylK1N9Da6Z9It+FYMTqo3GthJKb1IAYnZ6UZjjMFZf6+65qe+S0/e6LxFCl1ZN0PSSc=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
