apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAcSNs3l/O0ro336vZorj67NUGlPhvAjHHZjUvRtgX3dddSJGAZHvbytu5JlT3fVvDDKIrvPNwr5mZICbeLK8IIbtppeC6K1GvEZVJdN6zeNzJFVSkYrrN+jgbcDSDRR74qS3R1bKRMbSo24r1abmq/d/EITXrkiamf5BO9btKUJXPIWYURlUzDSAiNcddgNHwrjSTTKTQTnopNEc4UJtEU5AnKQI7y2j09Bg0O23hiGzWVUMrxuM1ieIKPNGKIAtV4jjWzNkVYRFCvrs+HWZ1HyTs8pBSkP3h5FuUE+rF0RwnZXi5r/Bq9TldVnWGCeh/J1VRsKLTuGmkHWz5v5NEanYY1jne8sYVUwz2oDu4jS4HC71yTEfPRkSDXaS46M4L8uh5WQFxmq/OcGMHWc5uzvwU9MMHS1IVfVURyZ7jHcyMz68q4xO9d/9/iB5qZDXREndR2fIKqCV8Of6RvtAzWbJHnLGtaYg3TDERz08Q1T57xK8WH8cDv9tTCoS4oVC5ruzZT8yMKdkqsq1aWYIFxqr6M8zgTvuMo2msqLP1Nl3st+iMDnPCD/2wgogkr0CKdXWGa/xrDPjIes5ItnuXSugBEUgSKVdLiExa5I5Er/0mE/488WVodVf8jsPVfVa9ueh+dr3hUhHgZO9/PFVbqBf960uJZZHpO8naLj2+daDwJoGm+cYafuhChLcG2xk04RWEL85K6awKiz+6U6Qc8XNTAvZcPUyoY64/i5ySRasXC1LgLNcm8
    username: AgAmF+1zngHs8FIQZ+Kx5jz557SnStaO/EzPvkdMFlDR6amNgSuURR0AYoeLNso6N5YCmrNgbBXOef84yO1eElilJyVJyDPMAwpjhk2BBMBuzdhyJLtrcTkDaycGDEUsEceLURlg1THTGZBNrSXgFrPgUwofQwyaEVDXmzn4gkrOXZooJOUMuLaynxWpOeeJ2saYa960osqU92Ll33tKA7ghCTSbL4/J08Nt1WeKqqYn/8tPGda58hiDTMk+KMlI2YlbEqiDq3+Z7FVJf+77NXpTYYwB+xTnJ7tAwhPrTWBfrThLPjLL7HahW096YmyVMeggBQ7310DhxBbG9xQ85wl3gX6MAC1on4Med0daQHFikWi5H5fZd9tK6qlpRnBv00g2n35Fx1nc+oawxkBavQvWRuAJKBGV91vX2X53eGkoSAfFwBGl4yqPGvy8btMvBd8ZA9qwiCmXfhklZdVv8o+GLuzGFqnlwYpnYSDffkeHrB/ZB+4rauKdPyLBnIp0+ZWciDOs4g2Jb6Hlv8qoNIzAW4L9s0ovpq7sPcUO23aGs0/LICccRvPlKNeq5zceKzbEcbSXuzjPBPydK7RwP0UtLS/eWhfLy1C4ydyMVI1TcIsN86h86qEwJIcPlBMW2ACes4NAJCu99Y+JDLweGni4enKZujyxJblZgc27i01Av2jntcVvgkxgCrOoTkKMV3bH8vS5vzo=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
