apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCjN0ygzerhcpMifI3kT1rCbj5WtLIf5PYpW2z01iwg/ukOC0l5gttn0QXjKv0t29LdWhNiXipJTlpZrda25Nz+7pyXmjoaJEe34PkVf0Y9181NkFRuWRU+F5vz6duElsO6g2NX1du9ez7a+CPPUCdY6H++QIA4SBdMfTbOuechs9Q6ryqapGlxqbOQAk/VQZANTkqAEJAL3sVyEjIgw3B2oY6MTVOJ4f9xmGpjKol/LpYldGVqiDtWX64lPomts4TzLvSiv12Za0kETSsCG4og+uRCw14wGi43ZqG1+MlTYV8EfnOHTU94PkG659jVGQ07lcHOq6RfWNf0EGpVrlP8VlOXb53PWlfqa6DeUBDsOKM9pgwhhUzg1cgoH35tMUUf9EInxReLgkWOVA4Nr+na/2Zgpd6QAnk5+qOzpDKs13ZgccwhPDX8CxcIaPv8tegO1gFCvJwkTfQ+dXgMOUBzjK4FsLLCnQNU4VCXITmUeZkuCkswkst4cfNME5GTbtcoqnv1YMUmL2mAj68QEN9UE7aTzu50J6usiqkCLXzlvNezQ3ysAydXWxACqLFVdulkaD7zA6Yvt62LEBADyhc+NA6eRFieZ2YmwpG6Hdj4AINRMTaEGqGuc58YiTxVDNV17s4kqeQ0F5oZR2DAG28p9bqsrt2MjDom3Odcob3qdwF6jZsgKMsF7S7tq+Y/H4AQMMaFmAew0Nu9+cvtfv0oz17UAxZRINoo/KNl8Ot754ixXZTSapNC
    username: AgA70T6Fwazp9oDMvYdNcaLJH6iBBgz+abMMs75bxIBK4hfszRJ1G/pFqIZc/T6S6ITJUskk54ZGVVGV8TRUdiziy1pD+jUbbUgJfXzhp7NAk2U+W8el60vd4RVW+FXXxdJPWKOrVVg6ozUV0AZc15NPF+NNwJj0r30JEuiWR0DqK1ELUoWsAdhGFgOxeqTopPAItClx64BzXrWW2GCPlUDy6IdwU4qqEwnIbsJr43ilrsMZHHdtPtJfGA735IRPeC+aKJ6612WzCxBJ174bNGDNpLR4WCv2Cm3RJTGwnB0VTzaLHfCdhQyFPZdewnJYz60O/n0ODrhRbu5NrSEGWsQ0pnzmY3CBH4D7UguCV7ZQ5CiLhlXlc09WhEARTbeuGT3ErAx9evge/rm70oMH58CfkwcDVIj5juWU3gWq+9bQWK7Ol08JBVCrSHfWjEa0ZJ5CSW7ifpMpYIFfg/BM3+q3YQJqkjmUqWBBiOV2yAtSFYMC8ucF0T3E8GJ/hLxgtS/9JVnJ7DKMgD3MhQzs8QLTNSN+ugef9EqjCucIQS2o2Tt7dOisLfxtS0DJV4UgWAswlmtOrUsRViuGEqHEbtDEGjrowj3WyUjURl/H0MECdMf4oH16zPpyIcqnwHLNnCuLaYFYLfg9fL0FtoLUcI0iAnqGDYg2hIxw8YSxgE2IiQkkFL60rWxCZFlWKctrY5sijIhaCoA=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
