apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBSUdPavE/XmNvE+FrpPtxTXnte2ydvL94my3WdfQR41xGuedPvV/KBcrtAQ6C4Hu97f5IfNv4t4VWKEMhmYfvwE1/NGFzWWvM3W2VlONfAgaiyjwoc7kkvTItsm2CIzfoU4Kk1Srt3Cfdax2PNFcYHEHh+UGCR8Ub5Xj5tTfCaYN2jlcFdMp1AGlysTurvQe6WAJC5iD2Zj2xp0tA1Crnzx4z3GWt1Tl+4rv2V+eb4C0YN42IS1Wf9SDFZEa/Ss2DtoF4co20DSXQoaC4nrVZz9tI91qizQv4RfJE2nL/A602EXkujaeYltq5O0fzB84iTHTuvg1UkjrBtHz0Tcrs0mkZSre0ehdqC6IYti4XL692dcUGRSKCdzQ91T7BHBK3E5so+drFKcqFvXiQbBjlJ+4i05D2aIOuV5g2x2mObHO7oN4er8xXCO6TLM+vdZXCKS92gZ6Ngzv66OcpD/DmfVO6VIGIY5FGdqo5bAoEQHhQ0mzMcKf8/Oq/9Kx81HakBSl1WfXh0Bo7GG5WiLN1KenvHXA0y8GauXPGuXmvLpYPdGUpo1/YjHpoiibRycNeUEhM/tJGXfbPr+3wPExFaJJgf2dyIqMxvM3Ho9Ze2U4W5w7Y1VSOBsWncF3f9xIZgg4SxH5MQbIKhRXYv0WkDaRyV+vvO/sblAxhKp4jHCvf/TM0hFYYSdqNASxNHmER6zqcsa5yXH7AyyJ7jfH5o/wnBSg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
