apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAinpuqLeEWOp0ppKKWYoD1APurE7/PuXTtenDT24z0B/8TRT6Py+Sz8gFkljOcWwMceMwJrFfL1Ilmwj5Y46oaJNxJc4msVigjiO/cYoNCzgobZlqT89E2h+OnsG55gri2MTxOw9h7NL90sxDWENUYlqmFx6h+Zq0grn300arfTzGG/btLFAU0t222VZ9v46hxumkrbi70mlHXCPcEGf0gnp1uyKB3jT95fVqQI8qtkuA9oHD6nh35xEJ2vVcDMuM7pC0FuTOg9WJS99TXQ6anXTnpmOdmzaUXjx5NjDlxuogWJbZUhxjaooyjvvOIelTlFqm2QoCM7sJuukFewQZ9CXdJVEVgcoeYWulpIjyOKESuFC9omrQ9vYBwP5Nu4x5KVK1mDUFBe9E6DR0O1EbNhulR6lRUmOeuKE5sVfNWtHgp/0qcjS4G4yL5RpWs3rLLXVs6deIW1f0cBJ0ONvKSsXJX+xqb0FQ5m/3XmfIVUyuS58Tn/j2Y76aA0Tzlky/uBn1XhCvB4k6XjvUxrvuM9rq/CAGZERgFQUKRz4j3+2Bt0Sl9e+yxY/nqVM3xaDZMlTL6L1/0EZYfSMg+Zsj0DyAGS1SkJIj75AazADBgiyBREdpWcHaaeDhfoApN8IBMS3+ykHe4jP2vv9ojMkO+oMiEo+HOK9D7tpi88YxU1hW13mYt7VzvGM+YUpMHbrHPE1/1A3PJqVVUM5Kz4+eWQ6fXwg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
