apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAnhh26qGXKsXvSN/zPB0wOqqI9ze6erOSSEyV5eHnZ0XAtnYPnszgiTdCJ/zg8lNZaZS3CwWqFcaNn+kOIJ03YG1yiLAlpD7aXxxhTca9zlBT/PMy3skbqRRSZklVKnHwg80n0OdNzAuocrCmw3Y5DywClIZ2l2QVgMAmM5b6qoYBfR27PMOzxl6izn7yR6HKF+2uluxZJXTORT+SHgDtFGtAsH9xgL67aJ1rgKNdSBLIjmgBrxNAeLKw8E5/Q00D6NGdi5BvAc/wCitlD3biMQdO3VBnlblHSrgSsCHJ0kIO0DhCotIQoY9JBYwS6Hv0CnPGOjiBYZ6nV0Qn23n8JIOQI3KJYbw4APuuQNBdSZYQFi+H+sGhwiwOK7fj47mBkfhH20uX2zMF55yzhAWwvLzCbNEbom9w1O6DgsLM+NTo2eqG91B6xJKcikwBhlDNrZq7Sv2mtIWyavgaIC8QDmCfIZhWdsoIovD6tf1kdcUxg9VH4YhXrohdGsOmTiSLROfL2CeTZv4EXojosqQPupylBhLWvfPvpsLtXtpzLftun9kDKlv2vRCBq2014nd0q6CVRk3u2magw2aGKEUx8H7/QPYbqXmxxkl9OU1QjJo6njAxamiSjF2qy+Gf8bpllzm3KpbPMSNX4g9d41haXIdHP85Tg9uWfmj2rbOpAX8PGNpk/hiQyvmc6bpzOVOtd0MAreX/uj+z3Bc1wZnu1OOTuwA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
