apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBWr5jUbztY0f0ceuRZ+RWc5ZppES6AAdTR7E9QofGSwZBJZWV/HRiug5gIXvOpi+0PBOtc5OW1qNQQxfZGm2CC/W3kP176Lo/KM294KpfjCNWq/4VDoBJ2zs6uY1DCraFh4lg8+FzEnY+fL4R0sOeo7hrTOwVboDxpjflBfgs/1zD7HJH7F5EjjZIw0rsv81lD6arz8fSWmux8HauXZJDk+monTi7yz2stPsl5m/gJgTAdGI6zXBxpgBG2+WkOqH+rNkHy7BnMaUNfET/LEiEuMOZjdEN96McK+H66lE1YPEjp/sHWRyI/85BfwmABCH8BEPOv/Up1pnDEtkQvjQRw95p678d3uKQ2JJobVwHzVJMccvnyJXTTTT/tMJSRZoQBCvqMIh0oE8IIMp9Wupfp7strx2HeNkAOZChFCnJL0ISeq39udY/hC1e5c5ZiHDqqBAM0glfcCyvx9/4m3VMNZeQNKBRLfWbj+rI/fD7MMSuJIg1nbiKOvKouuqkJEjMSTgJCn9BBbbXw/GMmFRA3lybCNr2KmPyGnmzLo/eaRwORctVT4E6hFYgzMBEGq3m25/8hcX7hygoJJLXiDP1vmfgPD+wlPAjRJsGySaV/+XVQ7sSFgjMuyDtTm+C+QRoBuHqNmZNviDmve6m6z3W/Rm+Zxy4ptAaURrqIzqUiazkejkcwxFkylPPy2Z8n7N9Xw+aLtd7Jkfa99oBWsqcLE1D6pQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
