apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDFpREmMENLe4SGo7XH3hTfWum9GgmJ5zf5DuHhe4DSoxxpYYz6vnmdHIUkgJhzc0rXxBvssszd6Rn8S4SwcaqyFyuHXJ20c/PDu0x6K5+lzf6tC8qIDK/UqlzGNvkqhuCNIDrWezEyxAAhilRv/NabIC9/z68KPGd7vqhMWcLBXSIcP6tarT71f/ltsmkJZSy8d39htOGhzSkN5NlN/1YqlUQbyrxIC0NDV1XGDK6LIO/cL3UDhogpy1dB/dkQ7BIGvWvtRgx16a3J7GyQyOH4lkbuibZCppoLXdGggFWYQXaEB0szgJ5FWGyHGoMXXEtLbLaFoNlhTH443whWgRHq/VNcwcbztShj/cdMCtCJQk/oaiGTv8WZE/237SXGS5ejKXukEyJblAPShY/7bOL935kWS0o3XO/aYjPhlEizVTmO24Pj8YKTLFE2v7fbs61jYzV/Ud6UadoX2f7oY6DRdddnQ0dLMvRrKScpf0CBGrT5pkyEZCPJd2OOTFESwOyKdl+cCq9+MmDk6dtB6AH4JIFFIxO+1/z3JFzNifh87lIQy3IKzDHTU9vrC20ZEB4oHP97vgTw4m2Uh8BFgCjPlOv598l2+Sqq15Ea8SdTg1NIuZEf34iNGZE77F36b/8HmFYbHW3n9QD7t2ICZLXTY1gc0Q88IvN0g6i/myeqY3yHCc40Qm/2Qf9/41WCR4BMpTsEhn+21b/eDY7TrZqYLCZsdQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
