apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAdSOypAjCGRjwdXupW1wS6PTPIXn2WsZGfrZukTd6QzB4p7VWwHxqOvq3DfJ7HkuMLvNU5VRW5gtsuLdkEFajviiFkYxgtxZ1l48DMICMKzx0DFmUskCf4kynURxLb6t9g8Uu5ST2gUJyjirTvgz1L9kvAcYKRLHWE/5L6+vXi2D0Jsjr3o1SYP4JozG/0j9B2r07S2SY/tSJQAP5Znt4h3B5NIi8/+c67AOtLpK8UYmxDw2wyCvx76VpNP6F9B2N/X+Ix7/6XjeN600Ilj/iiogbl05yRr8MBJNUJPGN+bgkym+i3twOULouwP8uTk9Q7VOQuu3P34CFYt1RSFmmL7w3NWm45JCKC5cpgBANL665N0suQWkhKqmdew1b0Js4pNcsl+f7RvtMl9vgP4pTnPnAHz7pFUY/gBmgh59blEtfirZOPhZgMHbad+Jsa87FcOBK17RAbmB6NhY1vNo9g1NoAUK4RNNIAZReV1uEOt0cAId56C29NbmG4uzGo9eJXVQDBzATr4OEh3qEJGxNzwn4VO0Tjkoz6EYDXjDBFSfOHkdSzN5PChlz1FInln/9wSa/1uc4BoznrecTv4Z+DWwx8zSzphq2QZwGqBSMJeh4jCCxUca8R75XFuPMAROYfURHfbC/evUBKu02lorF2nPVIV7+1nkoTFzdosgT8ElGzsqtDq0xcAtbQgXaOl4Dm0xFHhv+3NkBN3pei2kaOapa1Mg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
