apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBwwImoW2OVEXAeeafBB1085MMso1e5JUPxryNRcOx3M3XaG1WEEN+QBGk3BC5NYWUwogtBqNQWCwrcRPP4WuY0kHeFkxvpJ5vhY3Ty9Xddlvd4l0kgCalV6WH1th8vg4hLl96WjlcVtyEE971bnITFRtbJqgQL2/NmfiSpgYBI8GfDmHSaoGcmDtH301kE4dnOidMtjq8lD0qnzVnt1TM9cK/ZPfrJmjUmIXooo5Zwqw16k0rLQIXhllIcCrL+zxLzsH2DphpnG6bpuSxRc7FkwN+2aZFuJXuhak5KG0Liw82eemsRXOpkitjPaSREP5tk+vTWGxJH5fuGAWy9WveK09tx6VCnHy6FisNXp2KaWuvDUGeqhaLE7AyCn8KfNmneEgfc5iTyLK8bzZZaS/RD1N+fRrMfDv3JU4mtQswVRjPQI0v/5mDRDculMDRlO/Y1pAn6p9u1Rpy5KM5pg7CR6quviuvvDvM0K0ZWwR9vkwQ8ZEJV2DNrLMV56VEbZSEdIyZW9RPgjDVlvpy5+2oICNiTugsNqYDXMkfKOSO19lHIxKDJee0KkWgldAGDNmFd/Uv+n82nLi8rtglJuQFwiGUkIDO3XNA2Ysh/mYtuHjXs3AowJU3Egmkjrj8TnuMJnN4g/DHbhOOY2bq9jqRxN4naNNZveG2gDIjGB6dBzLN8rOZsGdeAZ6GcYjk0FoMzkHay2PyDK4WMEYLiWHPgPVw8rw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
