apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBhSjljCy+Fx0ahFyf9g7MnzgaZg5qD+PEV2Woj3ryjKr1oiby+nuUyS2esb3bBkyjBLn31KiInHSV6s/Won8rmIq79rwOlzT6j2kZZzG+AmApzBAigWTZgQs24yZlBtujVjp8q4uaWr6W4nW/Y8X2sWKe034nc7i+FinFHGB9Uho+Uu1d88gAgtusj7MjFXvz5U7iUWsLQRrDiIKxpyzgkn/17AkndYIEmLICullcU2N1LYNl3lz8yCyWXCuy+yzX9H8CvmvlwyxvA6b1AAUkul4W3yR9yshxEzEXCRhRDkcnlVchdsHp4xpjqNlTGrL4Cf9rI4/0kPU6v94j5sn6m1N0IMOymAg3hFae7QYb4G1ZExJm+sClhkHDlqNvqreM+zy3xadqMC9X7cihG3zv4A566BZLZF+pYZJVolut81TDyUCJQmIwO5BfnN8IhvtVpaDAMlkG92ob8FobGrWWuC0zQHC3jZlg+ZM5p2UUfkocVHFd7e92TILjmQaLlmoAyJLYP5HOw1Aw3Nra6DHdCLyoEEUNcZLSDcLwaK+/fmizvBs6EU2vO24qe/OwLj7TVgNrqLbU4mg0iwjHyoK18cn/VQLycFGfbX7f4RHEgufElxKPcoQu1zpwoeSQX2OyFlKV4eX6baYgBJo1nwpRpC7PKWopU+KXgBtyc8fIMtf/eUiNupRT6wdhBzSsex8tx7iRn7H35Yqbg2xd32MyVzKN6TQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
