apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAmQWCNXvdRGaFVel0GSB43b4d0gtOgtgW/w3EnzqorNEw+68JqJCgpuFmuWq3p5xfuiUXPitoE+d1Z1VhSjIur3DM4j55whvJyz0UAVo5qvRhekj5sbkI2asCqtnZ9MUX32G7Lz5t/VvRC0oYniJYv2iO0OY1NQMNzJutVVqbJXi2iLr8TuLq9wOy3sEU6en31GJitF8R2iB7nRFXP4rrLwCYw2HaTr4eyyu7f3I3t8MqUDj9kDAjfa6E1cppefS0tcIHJ7s1SzTTHt4WFKsPN5b2+gk27WNnR90KM/4BdLdZYzU86dXuteHJHvUv5pteKUWGm0bEzVDTwy5xRXtbglw1nQ4jxlgQUJ2c1dVa/MRd001EEGq0tphK30WaH16TuaNvNjkptfIdNJWraeCmQ+4FUgFMOlgFovNvObEY2+M3++YUEnOdUQXRcZyKvb6b7F67nUo7w1trXoOQCjgQYIZgr6jd14/wCshI8yauYLsoC+9SN9S5ropvu+tXLTgta0pzuMVNR+b8fv07W1gp2dzQghyEqyvcPqKXTi9n518pRUVK1L8nBEAcZwAbnkrUj8waZribdaawXjtW/RzB6mnTsNPzDOqzH6y6WgCokSktlBCG4o7zA6azc5OpOHhmLUcNrM4qEdII7FHrFyne+IbbmQRbX4ZOjEByEFB/jYOe2d/o9G6mCh4+MzRkpmnwBFAEy1Hi3tImGHfnC81paQmrRsA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
