apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAwdcpf5gSqJOS9SdS304ev8np5tMDiOcWHAa4C42uysQcJlJflLswTstEgxZmsVs9Ics8EnFOXxcxabXbY+W+pkD2EEISta0zts775zO7c6Qw2r4AC4VUjH5XftyJlvVRe1R+Fb6e/Ta61o+pbVmKTtCBLyUV88+HhcdMyQlhK4O2vVQ/7c70gpPSqgcv3l3HHuzX+0FCFR+diS1WnsTq0RnmUdrCXNJ5a5EZUv8llhHRsYDR/g0y3NkP/Ic0WDNk53jnwHoubuD1pODCG5rp9uiMP+b5qmAY0SnLIu09iB45dI1lzn3V/xIjYc5DUNbBzIj60i674ovPjRqyyAUy3Fc4AA6OUqlfsOaCcYLMrG+aA/OsYvC4JbP5nBrUrfXOst6/L9ka0T1BSh09dTcUvr2EKJ6PJFcbJlMYjgJUE/GqltO+tyYinRX0YtuVa2ejY5lh0QHsJ0qH2AVZAKbsyusANMRwnZc5iOkwjnKIyHTCoa0YAPJiw+iT7ogGlI742RZ8fBwMVJvPE+3zzNmVFcbjmslmQUN3TPCr7Pf186mkaeBJiPxywJadbtTBcQdvcD2QZvS8JGcZX0t2ZVOpkKYA/FZPj0k98AefguUnyIlZWjIP0rhe61NRu5GcYwVJOv4HixYtqOBNhuE65Oh1f87VLalLQpAMa1xTofEl05kh9z6nr5nKWMnFHxYT1GqwRNbcBs/NuXmuWSlb2WnJQxTX7rQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
