apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC156kfIZ6QEhdh/T/bTE3dv5w7gZKYzoj5m+7YT7ZDiq5EOm12WasBmrEJ8vpx6pVUm5VLr8Ih9L7Zzh+jGvLXpdKfCClBQ82vMpR4DORCNAiu8vDzzZptGYKbBoVu00annkgz5SCxHE4k6rRphaYoApnI3chISP65ypxqjg4V2CxCS7IxtzJPU2bpFjM0v9qk2a722Fuj71RREbA0PXks7nryssG6dTkv+fWRNWHziWlcZePAEhBeYyjqhxplfXJqK7KJQn7yw/bDi46xARdrxWsIOk/PGgdFBBVxxOVJ+jtL3bcN8rqqJxPrE5R1RTt9dFLM6sdm37hb6Tl5ZzH0MAjArh3LBzhLbQfI9ZHECMiL+wYwgV1PU/bus7U0fEjmN1pFdFKKNOtT0in4sA0GOXp+2g28OJ5z9nVylb3KkCUITjLKH6ANaqIFesoHLPLHKfE2H/tRmV6jt7o6D/7OzeqoCo3SODXkNy4H4ppQn0HudN24nB4EBXzP2oSo0B21p0YGhm3WUg3zildxLAZpRpBeIyp8P648SfXg9fuHrdoVBhtHZEMf+vXieK5fTpgywTZRA0hp7kuk5YRYID9hw8Jfio/+1BGHhysjKoAs0//WaUQyKABaeaWXX9KmRnXNvrhiuvgYjGFrvJOAu/YZIXWGqiVjfnubugzJXvnWOKMmLRodVmvX1sesGwHgLyBoVNWdLk9qtV2h6syZLgh8prh0aA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
