apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA5YGisAKEZqhmFAMzGG/3hKpIA1iysDOmOpAjPKCjoF4l/pWMAEr9qnXpeBOzwQqYQkT+L0QkcO9Fa+DscPYDEo+Jp3hyuJP+r3x6UUIUu2YwdmfWgFNeav3rBke9vbAV6PCGuMB8RX9q5X1xCNaxyUjAzkTA+kei5meqXtRi+sEE0l+QoDUH75Q600zEe8CPFWcD1kaQudTiK4XkX8G+lBchzQ84l2YTONeu8XwyH8hTE6eRc9ACruOBGEQD/UqYV+qHLeI6bAINOK6zNuksY/pe2d5iw4HwZrwl7W67lW5ImsnQL2GMcfWTbFq9JwMKmbvzLVahNmMNuwb/lytp57yIT8ZxYcgks+AW+G6f6lDm9yfhPcJHIoUUFDq2tuGPgaIE3qQvagwiBjMjJYnaE+9eRDPGUDxFyRz422DPuWOcynRdiZkIHGoOS5ZLC9bXhOTczv47elUkZOi3DGXt11WYkBTv+cvpKxoBq7XAgOmFPm66AOjS63TB1AyrSqe89LXecpo2pfvX0dFuePJfWKqXTCXRU+2oocwrSFKgc2KTO3+jjTOWwq4wwJ7ugN2fNDgM4vulj7F57RAEA7rGzxqfg08VSbD5WINt93gkJa3QpAi4hXmVGydbxj8uHmUuCxY3vYvWHRgvH76IK9NNn2sF4p3iZnXHJ1UxqKgTkZblTVEHkkMDWnAHha/HJ6w5b/3PwxA15xUUyfvslENLJNiXt+w==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
