apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA+VeBiVhohg+DEqjCukzo54YHb9Vx3dWS04WPkM5vHF1KOEu7Kq06OItRgXJfPQpsOpxgvQEPN4IeXA9+VDCyVd51ptYVoVmj0slHUtEE0rJavJc6+Mq+0RQL0hcCE0X9D80DHKJ8aR4/cUWg14qzHjPUBIfG6vTPbz7sRdMia9a+ndK0oWOgIMq+PybazaOZQj7tiPdnrQThALqOYwsnJXCQDThSxb2sjS035owSORwtVYnqKVJTQVqX0/Qb5+2MZD2TexHhyQbHZR+VWiNob52aipgvRitgFJRhm5MIbA5xGOprhbDwNseyTmk/scrWmMwkeYA933Gb/IuXuxKSbUzB9JPLpudekVcxPRMSffii+glF6Qdic/woHn+dbOyAgNJMKbNJo+icMXqEQZNKmc4xOOesMfwXMS4ArvhZA6Trh49Auxxd49/dZqozbxt3mvDCaLp2wlGiJ2834yWCP4hYW4wiZ69Hrm1UNRNS65RV7Pgxk5XDr51D0QIMQOCTeftkMR9vNYXYzekaPsG/3KXDeK/XpCQoJSwmllYjhDcH5adhTNLxQJJvEw1HEaiP322jKkSp+RlGoENB3s7zadpMALsOiViK4u06+QvTOrFGY4BLy1JcsS92fZIb9QULsIyCiG5Zi49tfBPsE/1bI2SiIe4LDrm2vAFD6DkRMhy7DvD7wMSadek+suovF2HNSoGVtt4LgnBw51BTVU4aHNFK83Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
