apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAdpYjeb6J49SOByFYfzynbNsmpG3p1XesXN+OxhP6sRNRIm6OwxzDuTrisBatnQUZppc2UnkUZIr7PxrBDTfY3egqTb44Kgquk3RoMFvtzHMVC8gFPmqXiFuiB2AsxCXkEJXWNUREDbO9eb9UJEjCu6UwkLFIc67f9oK4H0g8+50lNCZiJ058OrEHUJ5djTE21olsQTDjM9hG9IyEsj5SZclqkdUplWtvFeELDmDy5tyhte4LxVg3b/kcIcmXtHKn8qrpT/lXwkFFi1/vCMX4yz6rVAq69tSYcSscqhbnrz+6uqS3Ho9ZzLtCKNqONveYRacG4I98kJRfFk62e8js25tcpiDRhqCN+ik7RVugmvVp0RSYZQyMg5XyzCB/bbJVDBW1m7Kd3ZV0iwGagkiHPzPE2UR410KOSFXvFq+9hD3+TTKlqpVGmFwsj71skjN69TyHxB+qVuDhLtZILkb1CUk06ginXQ4vDvumI410s39EAlX7b2W7mAb4089tqV/Wg9ViOqQpU0Vhl0tlBssp0AeJN0jbjKfWz7ULJKUA/uoSigQyYaxuLVkJdjzFNd3HvH2J5daQwhzNiPJ2R7o0dh9AyZl7NMwe1jfoIyLC+n5uK4Yu0qAQLSGyWBTP5olINHYBb1OD+DHcsjU79Z98cwSEW4uSgg5Od5uWTvzBepKn1Y6ccwuHM4RIR5McR70MwSzdyQG4DJHKuzLwE2x2cNN0Seg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
