apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAazGIOWT707GS91ebDjWqdrRtdbHvYKYd9se74qrCgbf/CYZuU/EHxddqaVzzOZWCs1IXKNg1/IK1MEuRKnbWHvoRrbE5UO0f5cJzuJ3Ht5YHSkcY11jgEqLd+ru8wSt1bO30pfJ4OPfHWoXffX/Zfqup4ervjZT26Z0uJBuf4/jtcSD9RkdaW9h6UzgC1bilWwbvhKdabVjA+l+0bRdYSXG+cvOvqMGbfGpwdkhNZD5Rah5v/dC1agmjo4Zp+o3iofYHwSnfYr9Al7NRcwW29mY78gOTzsc/pYC2BAuVSuMhnDnc8mKVw19sJD9frEyDbmj+9BU/f+4/uY2BNMWVILMb1RUKs8YlbEP1kXCvbYZ8UKtc/MWahmPNaNhzW2NvWBtiLzdoMI1dQ6WBbQ5BV+gDBrJYJmKoxSnYXfcexg+PaqRCvILthxk7urugCxvo+0XaSyo/Q8nWUJhA0J+u8Pxck3zVQynieMHWHlKwFsibTLwbwwrlaKikMgqnblkOLz6/EUaAVU5VVhuv22SnSmJufbgyhnPr3LFlEPk+oHVfHQYXVBcwqZXd8RBamYog74nKqY2KY0SyH1Js7LGvQ/W0T4Qc13zQi+FHP9ZlYLwn5mWUcKQ5VQ+kV5vAinDLUAgWkBYnDKUhdQLFYi9fcfALzv7oAx6EfWH+3+JQXSdSvRuDSKRZa7+N7+fJxKS++MP0vc5G4whpsyAfT1KXFZd59gQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
