apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAsDMbepjvpNxEL1ArSuEVE0v7EsJr6oIqN8lC8KSrfu5sMbGHbWADr8npcVl0La6bSMyx9KN9DDRjOsLyISi1+LiyF1t+51WjhlFKD1JJsb1g46aImyc3B89BdypWk3j+O3HPJvIXQUo5JmKvePhH4e5XFmRf3MD5OTKpzmOFdgNd98IkuDXLkizanURsB1j+94EfkUyb/iNHaEsnVWQR6wFH/qgTYoXpwo6/SOH3kbxqpKLfCWHPIbrm8+rdHT/ejp3fMuihADoP1BXysi2rrZqKZUOV3ieSMnQj8WjL4X3drSLwL5R6BcoOoHJjpPcUyBbfyE3d3vSaR3KA1ZMt9XoTpUDoL+ZbadP30kbpoqHD+6mLH2t0aoM1iJ85DCaBE2W9nf2x0LLPBzR0fntXGfZuFOEugZVVnYtmo4CCJB4fAfN1BjjED8gKZ086MNSVTXnZ8k/Sba+mtJWw3Xobo0DaRGYdBWAYcr1RV8CPNxl9j3aVh/ykXEMv7L7egEfB2CZpNXb+KuDtVrRG8/6CCWwTL0yUWMiEPyjvzhfYVlB8jmQjA+8T1suGE3ZkWScE5zzrP4Fz70MyrhJjYiYi7X8JI589ztHEfj6gfHtwH06hYEKxT4JCP/U416nNxVXOokYP/AmbB3ONN61VepmwthDnv/EDIjQmTRlmaC33Ql3QczOgGXR48Ag1/FzgBhH/DG+LukOPfgQ9WVPjOcUG7m7GN0A==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
