apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB9La8g2Rl0qZPhwFMo13nPw4PQjZpN7Rwd9Ln8S/lL688he/uVbZJ2hNC73qTR57L0AkER0Mk8hJAaKlDOHdyE71o8OlxBm26NgGzCM00isDo3X1jdgpPQD85WHaKtmVf/qxkcvMJnt/L9fDpeIEI6X14TekbLjT0b8azLS7CJJldIqpF3efxo3apafq3hZm5kS+sRBCOnGGMcrXni0fv9+uCUm54ji/jbl9VemDAmSLRt64fwku7QYflBM7qlgu9pwSZQEuFI8r+1YHrt6QhDJdovZZdOHKEdGoav8sWvomFwtGmT3KizigB0zVyyGJ8WlYEViIqrruVd7XHWcAbVRXgOQDDdwLpBEJJvIcKUzOKCikSTwZkqbZ5AhrS30jA2ZYkJ59MiZHdg6dmtK7UNU89jbJLP4c/tafC6X4Y3knAIsTyTR+DqPjmjEVksBljkwann4cUjfdCynQzXqxNkjTA7XqvZ6w0JVe/b7ueDyITf4qyLAKJTOii6dtSEr3ZFxwkKww+BrdExAvMWHp5iN5JhGARlv7i74ct9qw8XXbSYIVYPLR2nuRBE/ei/NvHKk/a7sFoIzhD/TJd+zyJbK4RErELsrxJNtQl9eSzM1A4Urcilu7vTpNzaKrZvek+zGDl/A/fLah8fV6bi4569QTHofHx7sx/ls5o83DlzyUKTtUIwg5ZGKWkRqoAH2EG/zIFrYOcLeeEvh3KyGd/6tKGUAw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
