apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBHeHBclS2UYcdjPZmULKcfXLxjOXlCTWgwGiwOHobAMZMxH399YP3JB373VuZYQuHXk4Va0gVNBhNP4ultY5qsVxCRHC3lD33LUEzrjMhQ1ZLvwYicWedTYd8CDSVzM2hl/xxzPHfDFkjMk9lEFftzAji6wIopeq/+WpaAHfvV8LWdGTWYTuXrZQCdAs8uHGc1D8of6ezkjagUekE91HAkbCGyUTncXIK6BjKp2BJGqLAx6EKuMOTRAQJ/+stYk2QRT+UV3ChHjwZWrZklv6J0UaZAKkc1OlHQJMcZpYMEgDU90zX3+qszRRJWvm7yqKHt4CpMV56nmNb18kk83QF/FbPjMzeUQxiZ/FZYnpU1WG/2RQ1EG9zyXzyj4bjHaeTiisJi4b+FyU9nyiAWzbyuRN31xARnNvclkPghlw8qgTDSYEa1WY3OOxAd0BtHQM92rYQNYo/JVxwdIH5QR9PV6d5c15frkGKNUVovdYxRg0aHn+c53ZkEhIDDbHffcCl2SLC4suiu6UZM/22jtnLvogEh1Bf7vvFPS1s2CEZl9FF+mJBnTUDLF2BFSdNpqWoixM/iWyGA4aHdpT6qTPZpugG+5Jj3gHiyEOpgWsuOrghr42ULETlqnisT2wn/aBog0Nbm0bjQZnwBf469bonY2J1rh+bMExNpNxJiiulVtZO43kCPABASkqWKG9OLNy2cZQqSjgQNHP0rPnobIg+oa8LCdQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
