apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBb+4rEROvrjpSj/IDhBu1zYs8DYVnEOtBZa8KlUGlgamz4mmJBoSIbMBmwSgyxq9Wx8kZ+93+UlQXUTR5MyaVSCuUMtKJ/DRSjWLE1Zd69w9e79tJDiupjjXB29ofd8zsxpTuazgjyoQOF7VGXyymswgGYS/w3wlzm4PHPp8lwKC2fZUll7Jx6unfuvBB6g2oWHBKJp179mvC8prdxQQuB6LyUpVNytncP/o6wp24wZy7RhyN2uwHmH0Q4jm2b2gNUoxjREblLl6PF7rkx0AcJatYTgCN8Invn+87vxUBzsNFhndfFA7A3GA8uFm5cvKnnuQJoa711BOVVXKEXzL8cxa/8/H9/S+1dVcAubLuKX84my9ol1NN8rgUy3Xi2VPHxQ98SLPfiTnX7L/9dR+HOCwTXkbofnhDp7Tj12ekXBZsJePGG2JDe5HnwGV2tdAytXMl43xcujM8h2zELZVnW68D53lXRq0QDZS7SHekLkN3Mo3VCLqkACOYKCiGZmmX0wVPw6lUds5SPq3emSRU3wNPr6IyhRoxImIOZ1VTFn0/Ajxk4Yzjv1BTW4I05iE/yheQg5c4bkQaYlYNw8jB3ilGGB6OxS8zq1WtXsTHqg+Z3xPHayrKKtaN/vvz1bp+h2w3xAjV85ilSSgSXoyaSFEdAo1wV31AzrSAz7sa8nRIeLBT5QbYLzc+BqmipG5tgYDmeajDJFF+F/+jy1oSds2/eFQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
