apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBCNde3m43nV7xQ8SS9hUuGBqbImFyy9U/H1HseUWZIxZNbEHJel75jyiwF1yi0g5KDTZxA8ZHem92z+TODi2OGPFRtKVU2rfqegObZnmmXrZUvPOSoYbwojz1fKoWVwCnJvl8VEfWBQBJKwTAWcwUR4hPwMfBceEhwPYJq+mp8EoiJIC3C044ivLvda07WTSbDx9lP6SFcBKlrVzsX/GTnaULrZF8ksQI/cRxBr9mW+2d28qsbu5rPmvoygFEQAHS77e+Xbwr3YmR+uGYhHn8DMhtH6GQFopx9mlqHg7luDAaq7/gsu9k5tPBdIMbozSG5lvsdU5N/rAZGWzubqETln4DKClp30Hvz6e14VBOmwSwEFApRl1y5TFM/euMuD83+1UkqHhJplbeF5EAfQPIvGbMvDQRpDhneHvnwL51eDlLGpa30wPVTR2AjAIGnXpDwJvuc/8YNVUkHntzsJd2LjLVpSLJL1xR+2Gkqs4qe04VusRdJllQnkEq7HcUMjT2krA/cId5IH8TpslTz5TaDVeOaizkhFF2eUriWRvEJl42OYZpyb+QdquDvRmIeyg0zeYLuR2XD9mKuSxrCNSko4UHoVJJ6G5ZGdE+TKgKHCZO9EyB6eNaLZHOylQ3ABd5IzXtfK3twfg+H9Q1VJoZ7/nuiS392che3XFGDc+rXWyWJyxqFvBEFraVI11wqUv4gSGtubmx5FhcdGl1TNn8iy/qpiw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
