apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBBzfQtVDajbjzCMrJUgSu8T5VWQCYWK0zoDoYhAVcFm2n5d7wiNjs1UbMi2U2MDvkeaGhW72hXM5dEaLO7qLGGw3H9ylUKcMaYN2ddzSvCPYftEQdaYbgUbWOguhOigtLNi82G5FdOICCvN9BTiLTIF2ENe6ufwu9FbLu/dLVGdipIuCC/V9ffmtA2XY5Jc2KiPlv2HyN5EUGOA/Dyz5BomUTbYlOY4Z6wCI9dkdq3ICy70nByqQ7d34AKxoYM2ZMmPXKDu7YjBfnZLYayr9qjPRBEnM3w952vvAjRjHxVV7wOklKkGncXSCbM3DBYCm4ebmaMELsGcDY4eSQnmo4YksP9i8L/puysXXRnp/3X9XgarR6dPpDNyNi13DJmTGWi0cv/ud6GGZaDlPEZd/BOidmyS83ZMPp2OBrBHvBEtJWRvrHhnIGOjQS9CXz+SDzJc7uB8jxdg2oKa0n9qTt1UcVdgajU0mkigqKVHbqSQgiMk9+bWOoFK+vhY/5ye31U1Nh1Y8MabDUgrGCzgy1FY0ye2pmCAHfa7Hr5Jc1rOwpJK/W6FMltk1LaRHTvvfA+AvqOWDiGpEfpfsKG949ZX9uel1UlssaccML0w43tjKzCiyJ5pkh6uDBC7zIPo1gdhxK7B+oLcLzPAKzOq9psneN7P9MLsqLpCpf6wUsC81Xw9fSStPOqulOnUnoADFCdA72vN5KFULFT0ADAXyJk+iavVg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
