apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC8L9JFpessQc1Nx/DscfHFZ/tO3pSiG2kbwiEdWjkCVeUklihRIyl1GNiDa/6WbEfq7+Tke4wd4R0C4a1Hw3vpki3cC2AfYo0upCAJTapJDfQxqM0mbQFSiAKWPg7jytq3NFXxHYRocpwFMXa4j5gC4NXqSkq1Lko4IdTiaYpemSwBSd+s6zp9XtHWej1RcRqJ+9smp7zDPerxaQUX1TlWiQJeJe+nTKDSlghB3jTwIF+jMsmdIqxW/pHte9dtWhMoE2X5snsMjEFlPAyCPZKQa85CwOKn2fcXvVjcEoL2lP/+HKawFv/t1szTtyCQ8LaqW4upSGCPo+3vtdOPwf6bwKw0ktMbgS7avhcTxGDEenJVmN9jNS2WfvcjdZE7ckQWhn7GgysX93/dlgntAUTr47nMSEs9A5RzyqlLFdf5yk6qIKf0QjmDT7Jlul7SDji+Sk0uHt5UHS6SGhMd+ad5/804EM6UNDBdMe0pPsSAd05MQN2sopDihR928jzjl3TOq26tMkRiOiPGODqSmgBk5pTeLp0udQMLgYFuxx4Jx2joqRd/G0Ekr3/VxA6nkYt4xQ4RNwIyP6rcZZmRPetRMTaRXi/yJoEXN32uV4fZ+19KA6l/6ltyaz7d6o4xCqHo77y9fpZwSgYB6ImrLkiSIJxhjcdblTiHtFuJLAQ/q7NLXNKYlgJNuLgakjx/Gph81CKoDtgBwgs/whtDOfadiVGz4w==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
