apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC+TFyPWa9fsotGsw3eYc2ynANcNB94d1sftTv0uYp9sTlg+RBeVhyZgEta7YaWB2ngrHn2eOxgT/jALknGCV/jDUocj7yOQ3j+1FBguxaTA05fKCiV3DoRWFoJ86j+k0AtCaRjLoNsssmQTa0nZk+B5Jb1wmclvrNTI1G7DYBstqmT5CWuJUQ0Boj+Hei0dcDaLPUDVztIz7OzpE6ZloQhTYi4M4SUwEbSGdDHJ93UYndZiUE0QJHaqwienxeRKTp21/HiQJcAbnLKzx29+vGVHD4m1K5XZpuLXricnQECYNDvHJknf3xx8N5ulQ/mWv5viGe162AhBHQVJ3XRWmexOQHYNqC27RTyL3iyhr0AMpo9L5Y7DCeOShSxzbtFz7J7XrnINmTtTVimGtL/rbnbd5lEl5Qf8PAxr6JFnaZKB/rQzLsGUst8dI/YFIWiPUrz1Jh4FJdc1/g5f4zIYloG2waamwKFHLsEQmTw/oLggs/RJ8EglqNB2J9MjvmrNEI/eTTx1/lwuVWmd/jPQmCFDsGNa+8txjNnr/n41p01Yo46/6EosInAmBIAzbashEeyI2VHk0/lR+zfSlRUDQdAMezKrHUE4OxXcA3DKu7n/TmTIwKNvHhzpusB3z+QwOFnQ0bm74Urcs7wF/2d6SkE90UoNH14TCAdqH70Q3PXS2Gso+yeHHe+ia1t9BpNFc6a1iNHLIJXpPrZMlxrFWo4VO5F0g==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
