apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA4qe1AqLo7/ZwZ1fA9vyqfkLsXkBFq6z3k85DKxmHv1UOpCbYFLF8Rfcw8fHdleCIlWHoMsDCCBLSM5ctfkrG5rthF24vlndNVkZQpJFnVRXa22KrarOCqhTEQBBPVYsm75h90jBCP/dVT4euLCIP1jlcKpHm3f9gFpzBmHZRb3bUDGUOiu1eXP8gcEPxXtg4GmKrhriMSLgr5RQiHzaSrPOwSXuCEcYlSQyMurx4L6Tb88CZrx6bUsOl8wjoejxhIeN6olsI+8p96Le2SYGaObC3s5/xyvM3ynwR0Bu6040HLTjMSjZTIvx9q1JnEylLZPcQxQuNjlO3B6XKg5FCcU0JLXalAMxKu1e7KdvtaVLfduGKczVUUZ7IQeY471mMhhhEwJWb7lMHRwMRQ/+sMvpJAEx4nIptc+NKSIT0NBJJHtVWQOQHfqHAzyIQY7ScUlQyMu4b4zgAnuFdlIUUpu4UMxVteik4Q0ZKPmJIeiK3eOeihTGO1/Gyxjyy2PswWkhlhTHCyReF/DtgGg+gmjEf4l62PRwkuOTj5hueuHW/1dfXWne4OudgBaJnea4gvqPiTV1HBkBgEw+rlt83JwJyx9dIlEDIn0kVe7Jio88yyyykQV5kow+Bj44Ix9GFuNNjkJSwUvNwJs/1TkMQH4fci4JgQGItXOxRWvuoosMMQjv8zMN9jfX/ga+XIOk2SoHoAmf3r68yc7+0ilIhI+dBArA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
