apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBp8ESdjsZI/1VsE6S2P/DcyCwKOAkv/YglQct9kCtncz3LtQtiK0p5jklobhaDHTKr25DQL97ECi69XChrFhpc4VIbnN349j3KzppPcYzlH1V+9DxYdVFrRyd6cUtkpH0fFg2qwOI61gEajBZ9lxoQwoZWy7VZnjs3gDlhvjJ5FbbIgaPwGvdlK0Np9nBWDH8FzLGe0S1DCLbtXCdOoc1X1baiW7EiJoG9r+TdolARDI8GcYy1sO6rQBa6wve28zuE1OdhbAvUV6o4EA3QyKW2/J9hTv+CCu/MPCSXZC1EEspo7MYa0NSey2Zpi/ERmTVE0BSr+fxCMxHrzL7BCR/TVRSQhis/3wB5tknayjjQmBzGvO8Ta44/Rq26Urg7J7nMv2Fn5hoFsbPUe7kjAayvp9mMAczELFWpE7xs7rF95ofwbyXeumH2soevySbkApUA60Q4+84K2QXxKQ/5TyWimiVVZQVRgMVORcszO3vcjRXhHSGqYmxLaUgtqXbCq1q964fztVUAfL3j04pUHqzb9u0EfxSZJW7yY8sXfrQHJmAiQ14LmSB9thSIIbAuQgPfadIALLFcm2AEBPd1eCXxYtBLdp0HIqY0oodMjl0gG39MrL/xnA+aVdENNQXLLD9CmjipAqRG1xFgD2quOPR8VuQd7rIHIu4MavruUa9N/HfYwi/RVTxJJAShxXTgstjD898tjxJx3xZ363bChVVIyMva8g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
