apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-frontend-service
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBVEv6R7BrIwkfL17A2642kZzIOXPj1dxcCDgKPH7Ubgy5a1Fy/fOymmZ70qdiTTwUPsHiWd6q0Mpy/EnSXmwT1AmXwMDjpgl8NDVrrCq/PpjVKseQNlNrmq4OY2C6W50ZGGDl4JwY9DmwnvmyKftHfEmYV89owZrOtx/KVS5MeOCY1Bi0k4CAFZ6vwkWtSpaOgJcG+z+9VE+qm79YjyGx+LaJUU/NcWDRwcWqQDCrfh9mxCE21FBMZsQYpqcd44Asj0FIt7NiRkKhmqboH46wj8f4vRpJ8pfPaaSeZLWtARzM2FyTTuo5EK5y3SalZLnf2bSheKu9nUoEAbbyYj7Faqk7sZfqygHF0ETk1+vJ9JCJ0o53Ne1LBhPBmEUmgvtssLQACJqmneXZKGKmAQO3kyIS83haoSNsx4DEHc4bxSJZZEadoXF4p2jahrG28lOx0iHqUwDaAW8n+IPxKDhfQ0ngN+L8zKG/9f0lbXQnbinR5rH47lnRLWSBuB8/jZ1Ec2BDomSLLFMBxoHEGs33AU8dihHcfIYfaPCqlP4SrwGsKrUnraWj+g65zKwOGqXKF6NR6+GkrV8WWCyz97cXulDEGaAq9o+y49hj8PCP1s1qP2yC7MZoDWbzJEekxaVB7PLV4gZbhT7TxQg6OjvzRkHnWv7EokkOUHerYTb4729zbo/TWotqz0KeEMp14F3OWgoghm/yMZAWlu5x7po3yX79zUQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-frontend-service
      namespace: cicd
    type: Opaque
