apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-backend-service
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC9uWGkomm1k3wr6QVNRVQwSrbvGe9xnLJbTtai+TkvaV98ByzXZg9lZDa+69UQamFfzcC8iYSP/iT3hO6yI0Zsx51WNziRJIsqzHEcwxRKD6cwa6CSq0ZncdYQ94hSLsdf7qHai1RWtDjP8NWYLKjU/h8WtihgtzhfPmjyTboaaUVv5Az9mK8KXxEnEEO2PVG7wyn/e26zQTOUwv4m3C4JAS6TrAdnOHVw8J5lnFQcpnVSMluJVIDTTkkr1lXDYpEr2L1VuorZJIMsRQiLQs9jYTQ/+spG48EzeBfiIpR6JlE9G1DuC1Xg1fGJQwCeCRlG2kt0KJSVRJjnPn4ZQg3L5QBouWhIW809bO0yOKEuLUN87t93uWDGKTCJen0x/tkqSpRJZV7Klh+8ULLR8o65Q/P1Ih5k2JfOthWLaD0noGsQ646y6Rd1iwG2JUMlprABkyBojFBqw+/+yHhqItti65Vj2bSAnv3Krs/N8l4eiVe9L+7t8zVwqSmUeraLsGQRtUIBfMcPL8eINwy3ZPNKcxOJBKxtX6ME+j0uZc0fe9RzrsmnlpROT4iuTDqlkTuSb5dF6z42cOchyzfVQgDVEUj4VJLDZXx5g9Rs78f9B2s+vfdWNkP7yfDq4usEw7ZKHccwDKxn/wQ9AV26hTzICGOZVAS5gWL2flWKZWZSS5p/uASncxvfiRPgPLEVizoSQMkxz1Vwxh/jkAPxTFFUfj+/8g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-backend-service
      namespace: cicd
    type: Opaque
