apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-frontend-service
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBGTPghM8YiSjRYoCnIlJ/6/IHRo+xohQ62CagcTS90C0xlsILQa/vCrx4BU5M1LJTMGJip0tNvEFqqLVnGbtNW6PmMniNOOqIXzFV8HItSEsjlJAsu9gru+G9Lh/UnFtTqqIciBWqra9Orww+grYiwRj7mLb+qIUij5uzCPhts7nF3TMrapVE7Vy6+GOeYgUIBoGdE62NLqSrihN5dkssH/6iqk4Nk3Yau6bDaz2Wsb6SNSdmhSDCmRSEqklPIGWDOwM/cUXP18emM3qf1nBVbdziR1qQ+elL9tX39mFnujzZ4f+PauOmocXZ56D4uPOm+nRFZ3iLGjnmhV15UTBnRGPZ1OtPGcJatH2rFJ6B5vn9dQeEph0yiwr7SAbWZc0pdy+ioL9TfdquVx3BYiz/Lq96OVXVimLQn45kCZZfAd4WZ5+765CkgwQQUr0Sf2f9nC6F7gUWup3Czrz7q83Pyo6TB7yRredMeJuiTZVfpwXFtHToVRNcqrK5TF6nwQCkT3YYWnxkA1bOKoqMIr/QZU4eHnrUWmAQzNY30f5MBCMQLE9QhUdHCTGqmnsJh0R389z3Mgy0TDO+ZXr0366Ew7PqTFEDjkvG4qYe2seoHMPvHy+im22HG9KHxdTtAndCtDLoE3fbjLoxrUB4T+ulsH9SpN3/kRO50xMY6FH2mVUF/yTGYNugiwp+VwS6dUL5SCRy1dhKJu7CY5HH4n6JQtpcxDg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-frontend-service
      namespace: cicd
    type: Opaque
