apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCEKDRvZSp/u+JBOFmDaSYT9hHg98OjpkSvES7q+NtzY+3QDTK/a1gZ23BUZj5Q0wBoJKXDH5PEouk2zLW4MwmPipYEbWxeXTzTRmdac6X3cDFkA0QY6ywTuLUHRKZPBscA7605NrXFf8hVsA2hJ7dSnej7RyJgx0IaeNoPqD9yqoKlnUHO9QFgzwopi66yeVI9bz9JpfMTPw8sUt2FYP607Mnq1uLgSFPHfvK+AdqPF1qqFioIZ8eusVjIZ1qS2NYYW+MvDMSJKMFdi3VeNVWRpBrkz7+6eaJVvpAzx/7N3/zJQu7fH7F+neVz2RQpN7C5E2cD2HG5nSEJF0Ey71Sr2zVz1iVpO0nsT+OjfdGM2MwLMKgavjkunWIuaJyjLPOxVg0MDiJSvNR8zORZGJ9c7T2aUJQHi9YZr/aeVr+CYw49DlILb+F3zSsKpKBfOr9AAwy2EHB33crT6vATERICj6jc+2ASYSIw4wiXdjPNCdYjtDr3ZpT3+tI4VQeR7p7wxpN1UMx6yrt23YlBAKZ6OniNUxMbUipMgIRiYVZFMsDFA1InFtHcoz3T8E5gVpTX4vnUGpWjDEVI+NFM4hl9xheF3UKOzVDB5AlGLe3+l3JQVUA72Au5Wqo3HwayOWeSb7WLOcTPri1AtyI0ez4P4ZoowqHg7p3DfVBJuu8EIbgRlZJDrhbnBVWeMaRkebFbiuglcOSZx/iuzgWRDzeXAIOsaw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
