apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-backend-app
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBEoDTcUUerV/9iCKAhd6ZdwfVPA4KttmUHfzdLEcIkg2j/qflHM5UEaLbmmoPefKP7RxU9TNwBEPcGHVXWOvoB38jdkTHdLBHjvxG3dlQpgs+lRIequKhWigUhMcgNL/9AZa5WnTtQi/dKUgH1/n+JOXPZZnVV1Ouf/hUC/OOuwPWCw20tLsGSh8HkQl8JtfqFIYVGwX+dUAawk/AF2GjM3RC3SrZLZq8OYgYkXFjBDQkQlO+boUpChqh4g2x4zEvD/CwXVbOOr+VG0Nz4kh5+LX7Z/oDNUsLGxp/tbU7gB384kdG8K765svRZSelEN2cQrAw3jDsERU68B/EDxd76Huji3VBm++zJNS/erpdP7G6xDB69/O9cQj0ezx7ffp1ImmUOl51o0C8nd+a69d+Wat3g0DluLRXygQday5QuxCqQILzyWfyolIt74ISimRe90R6uXH5LXk7pgxiWxtQFIa/vl60mRUasqe9y5Sem3wmzzWKeGQlS7xFV6cQNhlBNfIHMQ+o19EpqIfsQY5ttJAoa5BA/xOxffcrfHRLDQvdX9qzcbPXEoqy5lixrzQuIwbMK0kgeaRB97FLTcKt7qJFKaDLH7M42hICtg1tvjf5lD1pQvd5ufedYyQvajdOJPadkEyb9sgA5Vg8Ue+vFr8HWDqYXt3S/xb+aUIoCRvY2ZWt9cagC9JSJniiUFQM5sjeMSPujaoD186uonxh3P8scuw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-backend-app
      namespace: cicd
    type: Opaque
