apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAifIjp1EjQKsjTtu10Y3Mkh6en49ykmd4qL3NJbxNcCG0/mTtHuNP2P9AVhHyjDi03cxnbCaf48zVAaETeEnKmU1Mvxrm4/1GOjRyvVCNu5U0pzd4dWfZhRljEYRtKi++OgY91PEDsueIyRV44yuyRo5kPFfI8TbUqFctbba1FtvtQQq24k3Qblal0COEpVVcVjAa9SP/+FI+jP3gSp5cRDpl46S7rFv3i9z9hmOeMsMMw9zb14Y1dCOIFwaJpX9L2JLMRobxeSuLN++uOzzH69o5SjOhu53QS5jGCv7RALNou+WLQ0zXDCEzmQFgeHE7ygaWaXSYsmRQh5NDxEKsftRJcFLko10SBQCjjH9ts6O4oV6RLXP8OpDvJFq3fWLJ7LbRlW4wWF+odgOWPEZoX3gySAodGds2MEKleTHYjsCtUjCLxSXv/yC35cLWJutpsvYSkjU0q0DDXyFm9qHnaf768IfSqoKdlKPFbRr9EtYuFKDMqW40VqgugyJYB/IX1kRTYd0U1Wdvr5I5KiD+6FG65iRY2aWnVYNfpvhx2jIKHa+pDageCDJfqjLIuHXYDEYahqL1loXbcMBUs7MHYhX6hnw4rG8nf5f07zPUTUQDBtgeGFvNaiHihE5TkcF57exbrj51KsDE+Pgxr3d5Zz2LIMYpkDiNgwMWV82fh+XDgtMdNWKoA4dt3EFzUaONh3wPvNgMfZUstzQrLlzIs7gG27g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
