apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCGUvo31lZHkBMPUbu3fc9WoVBU1UVjCWhIPsD2auYYRRolLgEFKJaCI7GKa3jPN2+bVo6101uWXEv/afZwMczW0LNGe8d0QE/ZtKQhGTuEgg3YUQQpwI17MvihPN/TPXzMVtLYe1qYFDDo3tGCRrY7QE7AuaholbKXbHl/EvWo3CrbAzQLEny1kPYAarsPUpXoAgA/SaL2MBh+2x4OsKv6/jctZWZ5+7GXy56+ysuoORwtcOH2fOStuxopkM+x3HgZcwMSPFKA78GKSxM/0Nb0ETALGnaTiI0VMaifeuTWg6ssACWPx5Q26QzoRrpPL6jeVkkv6rAJOIckHBlWOzHVZ7hCJXMncBp3ZjyNcw6soMSs2Mr/HQEoV5HewDLEdqOMxZBbizD5Xe5ZTfVWk0uVAjxP6r+fMPjbbwVg7+xk9giMVGPVyFN0oBUAvD1sqGeD7fN8TJEPWg4gSYyWNkrjsT1iO5tzZ9yrIbYaM5PaBW/mb//fYl8rR9gOkmm2pDiqlD+j7BKvoAyIKR7yAuZSpnTcjClz9xrbi3etbxspRWaTvbEjpMj3AVEBHgvL2988p6lHeWFvO3LGuLOVqXmylPhzvmbar25vq9Xnil39/M1JjEOiOGMo6hhipOvUK59gW9hEco7cMzPfcZM9wKXZHwttiyW0FWofxaKqSyKuOIHi8hTyDYF2d1zrW/5wjayJWtAMFCC8OSaDTWMzAam7HaLggw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
