apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-frontend-app
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA1jc/pm25LtienB1zZC8FvpSk555B6IHgYIuHKH1quP14cpn5rI3L0e5eOhrpnoCrCYqoEdW0zOq2/XWkGMAun95bu61JTJ2BBANlj+iVq93vDfm8fikRXezyca7Gkq43NG9DQDsB53bvS+rLGKNxpsnoyzeLfzkhuk9dPHe5DSQBKX7tKRtcSJf6oJ/ueTgh07m6uxyl/EAizI2UBTSmwqcJYPiikakK9uXpnmdVR2HRZscWlCOcrlUg3CNtJHZoLMa4n4unj3TFaf9PdaE1onTISzWdJq37HGEz3PB9mqdMJwkfVytrROeNkWlcOTB614owTh3QS0Ueh5D4ap2G1cMSPkXSTWUIyb+mqAfRzh4J4rwtWKAzBa8MaeuuR8xH4ueV5WlEU5Y5bQuh2CJ4FCACjcxjYjmOxMSof/MyBuRMVVaj71p4CHnBZ/Z3Tb+N+00CfMPzCkxOjtstJaaGHyZ9rEHg627zCevzkDt880fORp9CIRjhLr1PdCJg2hp68seIIw0DhGAysNLr3IujWibrkuqmRnrG07Y9BWU6iD/QLgkTqEc+iZjzqnNs5OAft4u2sJJFybbFzerC+n22QLCLCe1IwfRB8N4lQN9lshz9ZQLsu3k0g4JxrZra1lMyVdOOq81Yew+Osfuzt0dSfj7q3PSRdjTCy20N/IMZK0tdQDtEguXutfeQ4Xwc0DHnr7eSiEbJTScV+pX//XuST9tkBww==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-frontend-app
      namespace: cicd
    type: Opaque
