apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-backend-app
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBA2vi0KQQDCOUKYzfDcuJYlhprzkx6T7fcvBHDZabK3dq3iqQGlavZ4WtNPi8st5NTJ3uq4tF3FqekHjz8mVsGbM5rhkukwQChvu64DAYQebypHCB3VgIhKk3B2vu/r/cH6uMJf0eMnJ6kkTKO/8AHARSMptBRyAN8fGKZpPsUqA9EjwPMTuzQApcLXMABBKKl9ZV5r0EvCFeB/RgTU6HVMYEx78F5ltAsD1HqGfsSrUmbBblnbabrSGtclrH72Yi7igtOfoeE+KPN+jCejcG7T3vRKjIr0377Ym7SR2ONk0uKOgghWX5hm2ehfKxoSfFBG7nqXR7AehMtU/Obtk3rkVEqjvwsOU39EpBnP5EBq47YWwxKIV1nZiilkyT+cZGWqoN4pa9aMiJxWv8EbowNuHiv+DV2cZv5E0b1W1AjfE0F9md1SfRHhvWWtm9Asd5YOtboFHD/QdmZUEFzmU5dauI/jkDWABBN1Nu27PB36gdGDhkn8lpP67xtH5xWfz1xNzZorFOo4JJUYXpjFZ2qf1WgCpp8Qx6gFISXAPauNnlRUZLxpcnaLu4RwRDULK7zAVAfCf760seAqZyMcn2KmHTUFlHj7A84NB/bprfPtv35iAjf1nmpDZdJgVElp8kcrJ3LkJF4QRaIsdZTeccWYRmc3T1lJHT+2kgm/7hiloZyRyrHwADE7zkpBZfMcqp6joM9MPN7hBkP8CfnGGO9nV80gg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-backend-app
      namespace: cicd
    type: Opaque
