apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCkEWnMXinyifJCeo2993bLQVPfbuWtg/oiy//mjPi+++I1Jntsm9hRsreAPALHl4Fi5dnzqsQJ64/VGffUhbZgb3N8UaAsciLoPpy4kywVlukZz55A5fv/WyNx7kgK1mygyTyLftCcX++51aQcIxP4njhF8yrFFvfjvWi6VXuZZkGj3+q9v4vpfxgpQ8efVNK5bs+rfwqIk0AAFxfOBYEfdvoOQbslEHVSkvpCtQQNrVVH7NB77EcFj8s+ULSmgkbqmYtuXWMP/UrLztJpJTV/q7zBnicDofMBrqxuVjJBocFrHh2+KPXDfuoS8zT9BGGo0tKNRPiaHssmrGv427Ahbo68iPpgK5lij4XdfJ8s51uLoQustFZsqthglC8lFBOXbrCFa8NCS0Q9u2A4ISuG8ZaC6rTMLVmdPqkoCu94f5+y5bzXYZGPc9tyet6nIoEfsX6Gy/RZd1zmmE+NCOcQwCHwd2HH5Dp3prJ1zQ9xTqg4nowyvh02GLv0MGBc/xPBdfA+3Xe4cpwn8WyTdryaUfHvBuY0sSiUtNzLb4tizsKBd2Y5HsPEkEQpz3BDkKCiMGsuLO/ZCNO7DUkNFvEtI2Irsufj2eoMqf+QFRuNHLIB+sIa/awf8YAUZ7hh/sfZVoh2SPQL1azDA31sYFoY4JN5GvCATXAOLTb+6Iis4eqovfm2/I+CfjbMhibOpFdcoIptVBGM///tOsy6N5WPH+NJ7A==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
