apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAiDiZc+2eS0Y4OYcWTCLvxq1R6N1Q8BSe5arCCcmIzfOw2v/SGGGiOlv9ZxPLj74qpjPMrebrUFgCZ93mCIRkNDNMuUtlBKcjH2rG38sjvmbaEy7jHw9jkjXGSm7SMT1lade/BGrOrYk6u/MmGuc+nDDhCwE5+cEa5pTgg4ARKeA6LRa2KOVrxElvZUYyFBvzyLic5+QsJI+Evkh9hTejjgFPoTywSD8R7gYwmRilcFDu9D2PvE9+F4J5OWdblC8vuIxv3UdsZiLpt2eiDVtZl1Z1r03BHWrQ/3YaYkn731ue3g1px3rNYc2LM59imkZxRqWJ0vvRkB/eKiwp8gDSFyBCcAW1GnYzeKBpDvvrmO7rEmbMlrlpxFVgs1JBzaY0jzuJ4QJetR0y+KZJufc3B1NTu8gMrCIIW16QhsuWHZLv+gUI9LOh4XcUxYPgGup8w6FfidT7t2H7pS8ksUZ2Hp3gf66rCFGkdxfWQiZRH4bogKZOYaaXTpAh4uiCRH6nDrUjuMxEL3DxvAe+3A+AmjIKCLHd1h5Iu6oUBk4tusvuPDfa6l2dwZ34D45LncQyfEt8WPPJzQqcrvhI3yeVP+cXgBO6epADIsxCkqT1lb82q7nOp7dtoIzmxCRJ8J9CC6hZT9u3zYTzh0sdnAlEqMHUQIMIJ/BbxaCnAdPssTI86jX6L0PPlKgeH1rTg9PCZ47fWaPx08Sza7mSNZwj25tdrsg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
