apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCDBpom3YCsJzRksnXLh2gdqalpXkTBE31tBDO2Yq44IXMeJM1oL/A75SEH/NNXLY7ZBWpWx9WQ2tGAbanbMozDlfpXP1/LgcRKDAwKhDW6nHoc5IoKJdFYI3NeNyU0uztmX9WPMKSuf4+Eg7tOpYW6VFml+HoKJRJ4GoADs/wDXGdNrdwgo2EZam2ZmnoE9fXi5Kpatk0eN2oSpXJMHkQkEvmoHo06v1OaRYp1oFLGfieZNOhTngkYD0cNf9J1P3JkcHxkBGBcT8UZSYaZds9ZSaGtxtXgX2T0cSUa4djFOe0Ij5HRnRqfAui0lKNs0YUDgBXgoFUVXkzOhq2BPsMTMEgdZccJo99FGv0e1A4LXIHIfIeHrTtHObPASi5SxTXgdvBdvj4dbCSALM9sUxw2sWdC1ZsmnNu5JB/udDDL62VKJdFdaZBOtAQaG1PbI8OeTlo5NTA3f2QB7y54rKwnxS776Zo58c1QvG1wlgmM77U74gviiEv+S4tbfcBM89DSZ5+zKP0H67zJqmq43Qpt0c1WYYvSnNhQ8l5WKXQ3TrurvJf3nW2NAjUlLPQEKsgqcfgqzAQygHZGOBlyHFD4asup++JP/LDFk+nMQnEeqexUPMVqi3lHw73mPSmyW+mWWS65314Oo0sXIiMuhgxfuG3281eIW2terhJ0Hp1cTwTD7ScuLojyZSpSEJzvVd5PZmTDaYxC5osgdaBbq+3YSKoMxQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
