apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-backend-service
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgALEktpP/nuZlFUDzT/XJEmx+fMbDr2M6Dj4Ujnt2und8grDPWpQ5Gan3Fuqz1lWiEW+iFcb63EumumFtL1IzD87arnaZZmd0gPhCu1p76OgQROYRMq3ai9XP6ksCFPvCb8DKGpFhFUXrgaEG86YlZVDw3/v+LFQ0t9/YfIZzvrOpcInQuRqFVDzj21Hbq4gZbGCWSDx8YlO813EHW0bjODbwG4oV+X9m8aPgg+iN8nPg8wxgYKCqxC1TWAqtHfUjKfk4VgoElv5aiP+/hPfD27PbWKim1DS7XqrYRS7d+8ar/a5/TOvqbGoqc2aWdVKko2Po6FoCltQoMfD5vDnL9s4l/bYdqCPH2ZF+16XW/vosx4UDNnMRzTff/YbEWWeFbtagfEk0aORoKL+7h7yKRKAIn//iYkQxbq3OUEWPqeRD3kS7zUvW5sFjD+i6V194FHnQ10PXYvHFFVSKiBD0rp8Y46kcDaby22jM7gr6UQsQE0mlpI4VaL0lCiHMAVFgADgeR35s6cbz/WSbedXQpxt78r2HtA+2zuiTCwALapuWPPQD6bn8Gfj/jbSl5B6jGfV5GruhEc9S98MXaXOU5hrPvzp79SiDQ1iNTxXVXbr6zzbkya2KDvNj/opB/1RXyUBxING3i0fVZ1YEvzCiu2rpXC78L6WL7BEG+yvXPMvmmByZKys3Ny1KgXE/racCF8h3dWC/3edUPBTqNWtLfEMWHRmg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-backend-service
      namespace: cicd
    type: Opaque
