apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAoCKC35NriKJ2EeOyCoG0PDz+6mMGIbbOoZghE7yCG7Gjv9ftQ248k18t9M7O7W9vm8kBfQKO4C9B/9FR8ZNbezjv6vTd6Mx2fb28639wCuGz2en46vwSLESZqBjinXisFAUOZ3cGFJ8rhKoDpx6/3y1TKVEfRzRgjyUpSiE7sCExVKTuoudL9f9JIMl0knS6qIgiv+7Ju2Pnx4P2j2e1bsk48xSLmk9tsjR6Zpwog0u18dn6R1hIet837vqxbFEKy3mSOYeQ6ZQ3Ye6aD7ue243iKaswsn5Bd+uMa/Oo71xvpCsNGSg8BSTdB9RAuaa+j5OYeiiCU5Z1gs4NYGMFHbX9yy0EM7gXw9UxTbf09Lz+n2o+CoIvmXeecLTWrFSst8M7hwwMdZyy4xLYzLoU6gPMLNNW1uEeoZf525pO0BVOT8FyQr8OBx64Hc324BGq7uZ0ejaU8SeRTXOIlaHZ2aI6Pdx3HuBHf3AoAITRJeose4Fwl1EWIE2LVZvrAPuUjBj/5EEWoB5yKyCaaA9oXFGPPfpQpaal0/w+dJGlsm/FB0WWQI3Fh2IKg/O2R5wTeoKfWqtw+mVk82ZRL2WRNa7tXUf/6gEoFoZE93kRj96danfbyVe1t9c7JP2h/ZNLY1Z9i5tzF6RW7NndejqoW4L0SG7CBZuh3RG4RdXDwzLFdqOtId4BfPDQf2VAnY3uVqYSW3ajl0IuU6Id16FewgQohjg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
