apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBcB2Hu+DCj850AVeaARDyYoS9XRggBS2ZYbgR8F2hKVT/3fM/y6cVEIWR+ZP0W2BJvdQfZN8a1H/GmMR5lpAIASZdTlFwYjuB/qJ8aAogSNYS5WbCgWVb/mOGZPOG5qSlRT88dX7A8sScjzg+0TiuqnIY9DzkE3MiJls/zEO6bI9HXxqHfTPS7aKKHmkkPds31kpmAduRKHM0VAD0dYPrYuUh2FSp+c6uspgK8kzc2h/K49qyn4jUpeSBtv1i8xuEffEefauw5hv3a3ZbyWK4rX4AouSvCFjQ14/etmM9+Xx3+S2WoZRydQPeV6a4zShVrxShxo0cAjzOFNryfR4qIBwp66AgnKd/lTghHhqo2uc/kNyDIMTjzSeP+guDQ5Xy2OxkwfFgTC3P4KJ7MizdkriYNqS9lisCWhqX7w4+adwfFInjL/hddMKAnW/U60nz/utiqwmeZInavO7oJz3WXwMIfkdMQkv6TfImwcrBEuU1eE5wmvq3QMHOyPKTvcu4TdrjWE9Bhx8QmkeaAznznrRGffqr81P+a6J+AxzM+J9fmAY4rNR0GCrsD/Hqh6E+sLktXi4csQebXqI7snBtk1BMiqsrKTRBn/Ssy66PtjeOfsRN75i/brR+XOVfaJ70EbYkQleqQS9gctvVxqTctlbwisk8/vXX0mLaWxC56GqmAS2EYSCjXk1rCy+5kAFJRv6D/Tx9jZOm/j7R+aLvg4sjH+g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
