apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-frontend-service
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC7jrk/WUVo1av72q4u1CP67j+EhJR8IpHS5my2pIRNwCj7XfhJQekKwqerLy+kWFu579J5rnYQP+euAre3Qx1I3FfiLZYfRIlZSQbz23tHyKzWU4S8Vtc5NKPAEjT8Rt1sT5X7BJME/tEBmKWk4cyiVJfglHkjyKc1R6b8MRQ9Aj/h7RD8UPfDVToUTv/0me5SZePCxGoEYMlRXA+JeVuRlRkDRC0FeVYJqtLS/1906dhHt3pYyASdm3ChPUxSt2pXKbnbKUcgWaxETPHJd0JIRomNpEnGUEAJwH8wTJ3FlqbsnU/2PHO3hxosa/qhF5/DhcWfa+SREWijWDSARyXd0NG4/BSV+QaNLHlPJFZ2w8yD0H5gtg6G2H1+yOdndAsJB3VqVNrEl3B7mX4GGwCduHwM76wvjgaHPNYyUJjUq/ln6001iHYINFOwQyFF4dgktNQQRInBuDWrjthuJ60tLce0DoY2S3TA9cdpoKOZ58OYuHyqPZ8ufuO8LfkTMHNSfCXhbd+T1wmBXkdB1fNdHdcmeI6VaGfvGRO+T4kIk035CpXP3AZW+kwd5JUFYfOgoGn1owlLA9AUWKk2yd/qNZ2ZvXVXHdmoBGSOfB+6U+SF3gKldD4r10UR0aaIfkL9t6pZ2UsSr2CQqtEtWEDbDjqGsfGQGVZoCKvnmuG//iebm2MJ1IkvoDAZFE1eP1WysmtnacdRYT9M6DBokydWI4wY8g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-frontend-service
      namespace: cicd
    type: Opaque
