apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDGiFWStxG1OkROr6vWufR92fOQ1oXjwzMNMHIsvoVgD+LNZ8EfQX1B42Hckd/vPZhLc3z5JPakBeR1+G1rR1fBtUwBfWYhCO+fS5S/BozXtJw1On4Oa64bYLY9Xxxy3j1Oa4ICZeD1eAcxTTy1y/wWAOL5qEtHE6bx9YsIiUxbVtcHTo2IvhyjskkSLsk2MRIXLBBYJMUvk/4FeAKWC21fEkhuRA7292XL7t3STg9HOTAX6voJIZQPQMGU2I47RXlNVckfEfIkWg4g8BWCgqqrjphS6Gy+O7SncbCnFZXL1lucz8NQb9pusuSOZEZBNBORu2KRdwYtKe0swDEeQsZ8LSO1ISImm3Q1m+8nsGWo0h4wECuRCSmy/LbZZYm6KkdXFHlM0DXr1mfbStkRZWZYckYVyNOXipK5vhdrudneiQCY4QhOeYJiV3z15rQwJ0odAo77OzfDDkx/St2fHvA9ZH8+RMA1yLnTIdCMTtz2mKAkuf4O8tJQZl3LiFpsWayt82bQKs49w5BJEjJ3XOWAgla94Y4Ko5oXAhSv9JBCUUmtUM0EUhcDWoZjtl/aAmnGRPP21GioOrO3m9pPyg6awaEOEQoRMJ9a5KgdIjNv76qfONUFi2bNWycQZrgnABWnDwg8+FHFxhCpN7KP5z+fdbcQUFuMAPfNaFTI7UsvCsFJao2lNDqDeSRSwDwgEQLyGHUJJUOo/hJkRCvLq/ySIuSxeA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
