apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCyAfBU4xjYaS2fY+KprEg3EqIjjYblWCELcBIW81LQjkXKgxEav+ElWxQ7ZY/JmlnWAVWQesySQI9U+pZkqDz9zIRXF0J9o5RdoV1FJVsYXHb0MR/1UjKD8J0/AZZAuUzTVX/SS8VPCxP2njOtBQeEOJj8h+XqN6Gel6ZahVmDMK5zeMYANqFud1CIyKeWjaiKXou07EcnamJg7eTabnaBPGHsAWkveHqusk+HOWPUNNi0J3Lk/h3nVMnl2SwvHOjqJiunUE9Ylt2g+usPwqU9UQ6wcTXEFwyr+4mMYAtAai39XjWDpLuuyCHaHeVV5sQzXDtliui+gQnaLPpOOVCDq8D2iVgYU+P+IURJ6RYmHGAkcu3CYWaNxWsAzcLaOgFwNZ6B+mbkGzfE1q7HqHFVDrnB/Ko+ndjbmUpCuKhC1AOUuiHSNKYuLwbeYuKowRmUPx2AjDqv14vOtG1vQJ6Zy+KNU2pCI/qrycjlE+R1cJKlODc/tIMdtX3Oe0yOiBka5RnX930EEiBbRF/zHV4Wg4YhIhPX4Y1ms7LlIFxc7/Dni//e2LbSxYJl/cbXX0SmvIXPV32crqYzW/Wf/vxcWkZx9N8liqp7LuJH/LkWE+znTrehyCO96yF83MGA+kuTlxE0xjaKvx59/xw8Iaqzfqn6LICYiDux1/6GaB+Z51TlEX8C8mVlSeFN6AXiHtZyMR+EgKpicUgcOW/PSmMyoGzMlA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
