apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAPCPVnWN/sT8j2PAkvG4JdOlek5DgJtDwDqOIZsi7AhWczTcInqH3grFnWuE5XulJr17e2MeJRyONgfGNBmpdjETgLSIQPcPBAHLOX3NTdMVAzjYZXEYaOfXzZDAAi7ocsckX82pMB1zL/MpxbIsugxcOPjGxXXbgZYw/MsosGYrv1Wz4G0n9mGuv/rDzec9tDpf9Bn6R8QfLnJvvVJ+LowzQGYUFWMuPe5gh9vJvlmT9hoaUzL86H8owYBb851jC50l2qPR1gdfEewbEVNnPR0FiZurUj2U5vohwhzOZPdCVkIjv9LImKAg5wU7jUvYLAAhYWR1Umw812+gpL+7c27ru6uD89LEglvrpFuDCh63EgUL0qIbhOjvEGWQ0aIFK1IJjhZIMrACil6Z7b1teAzFCzM9UOce0AKngLo1dQHEwgjbyip4XAAoL7Evj5yw5xoYsKlUQ00SsRmF/yy292Gr53HM37BTJQpccahzJHKOeZYPJLoUQSjbl5JRLsx0SkvVPlaKAeVwN54ca5uzfAqj8ZQ+ytGLDDuad4PqOE/fsz8VxZw0WTETXtrlH52KPQDlr2pxQfyWKmPYueMagFCEpzEb2mR0wnHh8W3D9WfUhC3U8U4gt8DuLMQXbkt5sBG2jCErSWjTMLsj3NfmghZOiD5aghb8GlxsnyD2ANbTR2pZhx3CdVGs2gJQUvNtqsnocSouI5s/A1MXGxjzm+Mh4lTg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
