apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAN5Uq80A783kWsJ8jQK+hEA6pMro7tLOY2dn/EiKmSRLMMnLRnt4sHyD8CvnrhZ92ELT4z1Zp4qvkQPOvZxkbF+goOLiCywuwlm9FRWrg9ukp54SokasKcaWiEmQ6hFAaeJr63uE0yWpxLYDs2YcQvrp2q2d/YN1xSbav3BUaLfbvNWDBB1Rts7NncBmdsy2S/CTTJvZpx9Oo8qG6d+O7H+o/8YxzGmz6mt2RXpOt2qvq6KHOt6EK++tscXcKlY7VdI3pJxrTzp4OL5pJ4QqofebzG2Fdk3mZLc7unL1W36S2yZN4veHQhnavlI5j9WEnav7xl0TVjzBl4A5wJKzb64hwqjr3aQttev6aGt0LioQXw4dRrOaZ+L5xqcRmgExsnayI0fx5WoGs2hLQ2AurSkF1Idrpdu/UIXHMGUdHzgXEP/4/jMX8PYEmPS6lB3pexVC6O4iKySVVStlDG5CBFLsPyLc95Eyi94ueQGTsQDUlJkuSXLkK8Ufti1Lz0ha+FDAKnSNFOBajl6+GKJcw4im36dSG1oJ8T7nCxXf65xxDgcls+jAy0BBD6wgGO+BqdlAQh9jx0ecQQndAgscH9liiRTuGukDiE32raUh0k0HTSIK6ty/X23p1VFn9H3sbYN2y/orpD4lUnbjkpzmJ62Idr2caBZBcCFEMxJjwMQ4U4MS9As1RHG5lnfb/+3sQpezZjbKISjIVohL2+z7AbC1CfRQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
