apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAXZzVnc04x45T4tDodOy7DamxHtaj0p3f1cHyCw3VRdTCCGIrlXudFR/awHcjBJztOt0z+uGaoS3epkKrKjUXqh8xYdvyoTheI2xtQ+j+cDjoq9A5EVP6B8TXBAn0/Xjm4v71RuCeNJqnKeBmLEbUAdurKEgrCJ3VHhMEq/a4dsQ7CW1UErFjwrU6ATbR8h4GLMSzDHI+KmqMdm2A4H4QeJgTH5W+k5De47XxhBAKkZ05oQuYuB5mr0U/9T5usbB1qRZco5hEyVc4yQPGD7uYS3N6Tl8V7w3Xiw0qghnpmUUWPHzD5/n7dvanA2ncVu3vYWc5wsHTqJyBflAhmwcvHll4D9ccec99CAPo9vtBPdg2lGkLc3o3zkb9qEEe0r+MikepypDLuIbvmRhGdmbvjeRP310hcFp4OJMBw9sZ+ZJE2xCnn7GnZZXD5WvN4sLsx/CqAMs0TMLacMh/VtNArSm7PAYG5UWHVZ4RxL0tM5R1C86Hh/xaEQ/zp7ssHE4RlIB8O+RZWzHv82ZvwVZfU13zTLhNltxODPYvTIwYaMpggazFgP2mx8Lneb7dUzPTfYOV0RPMAzkYoGYiLsFW6+P4OGBJfWbVqAubb5jk13hhfBgxL4X8xrOEjRbFaj2BXtsj3GMIQWpscgkIzkHumDIyO+DxzakYSeOZboZ3IWG0+Vh3TKgTWPsR6Tn+d1ImQA2ID+mc0G4h7InThmDyFlooqpQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
