apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCwsbZbh+Ie0IfE/BAxNfsDgucheAyz24Do9U2MFdkk2fbTzKdZVmofdTTci8oy3y0v8o57fUOITEEOuVccKd5BsOXatDFQpoUsXmD/YfezNnNVUkQ8OiOAX5CM+Zk4qU7KHc35XCAPmNLmh1xzdsZ2It6TvJ+36b5yb9nsSNqHdd4LtyHw7rC55TVhGEQH4X8jlQ5sSwG0iHv8QIWVwM5XgSrbaqL28eE2I2d6g13SfMtxVm3wkevVq5/gMZfpHj5j/ktoNn2Ilnsm73l+egSdGclNh5pRaxqt0au1YPmu8yrjrzf9ndlJlizYByu76ilwVKxUhCR/XNpfIOo/K4aASxngIQDRvsJs/MczqwQLEzDMYXGSNcOWFXy5TsAwuzQLD1UkFT9726U6q9yvM3+Eqj7BmWyusR1CBwnXvYkBK/EVQwHran5em650bZViWMF1rJcXzNSmXbIErrH6dXLHgIGLcnxosacHl575/bIITEwO2LSNWlvt5joOAXOPqXlxq8cyB37bQiX5HPwuNrDgYfKBg5ZrqjxK0eJSnZspJDGdcPT3uWGnpOkjbrxa2yg+Q5dKiP+8J8ME8URMvGlhwsKVwemnEb0mQsu5RbxNkR8Eommc6BGbW5a/rwAvPCJPGF/iiXFqh50p21PqD10ZbtbtPuM6RJPBauFFztStPHUa6mDSIAfshULI5uBMH4o9CnZMv9pGDpY05yAqSkgNZUWnyg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
