apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAfC6X7LTh2elMLK3cvmZeCLPp8nxrzBk5OF2xqnxsxZbJH7ejvAunV1ZZ3AlvI9Bj20tHjQQY1dkz8CYhuTTt8P5vvdtY84mxGIKzZ0BZCsU4TsUTztMreGii7L74sgyupmQh6qmC/vc7X+bYE7hNOQ6QEKGCSuUR2aPlt7ztx9AaTFzSn0wSpNy6aEQ0yyRt/N/e/85BtUNBJgggjAwW9v7MNSew97Gz9+fdUgsZrY8YttTZrVSyUvVw8sh/zoxTHfLD+WqKby5c4Tjy9fyWaYnu7Bb/XZSsr6+Vrx6xZQSq39NGtCr+x+gmE+NrbB9SkiAWOvoxLLHHpSHcaTElHX5aV98Z6byqw685h5tbsahQtr2gC8OXAHbVJhqmcxeMAmvP+hGkDBAHLNHWj22Sh7+ULLNu3C6TvJXmljpKKZ/MXL/vNayPpwNtjD16w6gVpoWektthn+ka1T6CVfzB3adaC9e1gxjvpTZNd4OHqrCzDfkHogxGzP/Rl5lU4n/4a1oWYeetYISLiHxbUcR0iaCYJZ3gd/Z9W015FP4SdLmvrT7g2RyIPK3TQxK7Wbc1Z8zu8OcPG5bzdLUC+h2Lm/7wxlrg3mwMN1cyZ3YW44I6iyqRKvZ9NF4aR2JG+6k3rUhO8MySk3zyfJ10jNgATrGivzInyRaDyjHTb/m7VFJ6Yr7ENoBMFhRMJf4r8mm3izn0n/JlN7ALQ4Fzfi1x2toe6Dg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
