apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-backend-app
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAR3/Og75FIymuAKamhOMOuiANkygyCjXYIL83mAol5ek46IPb9OxclsNZqN5kstCXqhPQvN33l42p08RCi+0vr5NNntIRZJu4SrPxhCdbLXKo6ztBEqCE0Gg6ejyR+/0HLc5eeCXHgmmUiM3GNyCY2x6lZPIb8NhCOruGXCDJ86Fa3DpG0pOWy7kqD8yjnxAg4voxoUgvibKuOXGGmBRV3QURFasSa7FwwVk9M89dXtecNQcK7BeTiTPSDLLXyrzfrDlcAMwnODyqY7V2S6HFyA+plgI4ZQmUjPv/F8UDNcx7WaR2Btvq/0TtpW8CjuuUK/+g15R/MwwTIPZ7NEaH4VMFo05t2Ej4Y9QFgFGQx9nw/2r+sxSVPBlb6N3qOJR8Ut8PLEOkZLDEEEesXfq4HfYbC/sy+An7zw6hcCZERt9eVOq/1t/H3P0s8L333pJTaX2X+7rP+s1jE/0xJNrP7oTwF0gzlnp81ISZNCigWYz2zQwVxuUppLY7SIcgIy+L1h1x5zFchll5OfmVBqEHlw5jYo4nmhUc5qOHR0VW7cdL69pyMNJFGmNtL8SAw3vMj57RC5dOoBimGFtLsW3LFvnMPsfGK7x73nPbd9mbh5JaZkLnEsvR+rTHB7aOtu+WOKMPUSYI2X1YyIGQBn7uT/N992JkGuC9G6G+EKqLcJYxcxljoqqjxbLS91GbcbV4Ivgr/tZMQt6efpBdcJdI/XTbS0w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-backend-app
      namespace: cicd
    type: Opaque
