apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-backend-service
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAjAzX6lgPYRVCNXJY7OpXTfUDJv2CSg+Gzq8z03Z4YlGToG93pUsykR8LKNgbFFQazZmuWYdff//pRJnePirAseDWzN0lm5Bx5Sog/0y0W/FsdhxVYAH/6Gkfk67T2tHoAYHFr63LT8jL4m1fXMJeZHnkAfejh+bxKnIH5+DDLMfAfEacLJMtucwKCe5RzdD8Nd9NQRqIFfpH3kDXZ8QzvrNiD3u9oEDbIBXo80UrJmezulQRlSf0PazZKh5zzAkzndQk3tAolY1Rzbv4y7/p54axdHdSoAItg17yVg3TGdfg94OnwlrVk4gz/GMpReA8yX81KugpS4TSpL321uebI3fp6LdZ+lv5VKJyjJBG0xTwZjuuc00NqYIDcyTwVi+KRQEZZeYgwIbM7C1EV/Mss0IvYBfmpjP1TjDZzTd9VnfFr362a8hOaR6yONCCiLmv+SBPP8FeGb2ZoFMhTxplAPzVqgOA9G33bq0U/WWCRQ/23JoudLQnjGnP5CLjvecM2cXofGr/lAaKO6Ql26GgSQjlzEGnDkrIrmcZWD1//0aIMOhRGfAwG5k2p6Em4o6+gLUQXfZrd/TGADr4l5FKFXGBSJCZ8olvQxxCchfniY/0D0ufSdjAHkEfGMIk3rE04jwQxqPHuqc3M/OWb9K/Y3UcHwkQshtuC6TZqd7wG6sdc8NmQxOl0nKDX0tw3WghCnWl98i2R41CYJ+Lb5GPzoU/wNQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-backend-service
      namespace: cicd
    type: Opaque
