apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAevLDSNUm6XoccmHKomLJQUSLpOu58QZ+fPoADB5fTmBbSUwzz1mcvdNdzSc9fYT0fpycpg6lhvu/jOcB4wLG4rR5GbCF7cvA7nBJlx4EoBtpXJG+tMGxf1NcF+oDw/MOkikkqKba1jl1ImEwzwOZcl7vUbCgHy+5u/eSggGTxSOCo8N/uSVTQ2Pov/BLK8X8nIx96Sii3JBRPEId25xFKrJO8qwSg2ckKWA4WW9PUmD7rtW53Z3WMxa/dqgO0r4hdCTGA8/nA5oCJ3HdluFNv6Xc/nfRo720WDFHJFG3v32qIqwoRNIbyeJM8ux3HMUBxVRdSUgbdg/RqMhoS50vwfbgHbFqHiVVa8nAK3Birkn1EbaIcNe9IVTWQrQ4F4Q/y00AjTyAitgOPGs4TTnZ9jPSxe+YnoI3IJB6gsd4lUCQp0L8BUDFA8CmfR9COusTyY1q/hGqWywY0q4ZD/fhXRQYCsM72Y7LnwgCsy5bG6rEnhKiOBHA+RsWXaMVEGZplx7KUDtAAGDfLm8zPl0/XvOydsbbe+H6eb9TH5QHhCSGAEleSqAQDFfiTNHJya/y7/YtJk/V/xtomieWsG9NAqWMUBf2azh7K9SLH62B5p43dRiEmx6EbwMasUAkSuSyTjpa739U+Bi+nktPbR5aLF7nrT3MfDa8++DwExbi9s06BwlSuOCiPy4NBlY5yqD7mKaFe4XUOxXMn8IAc0jr78o0qKA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
