apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAlk7G//fKx825Rn3sVEBOsmn6KOcAyCjR1yYw+6giJwDkDjddBiZdbiYqfy23CLs01olMDc0Yw6Q5nU4b1diet77IJ6wj5Tl92HOUsRhrrupyFGTnFvbV9M1xIwgkPktImBQd6i9kU5P/JCzxZ4uw70VDS6SGOeMfRJTlkB7CuKLWBWSPLUBxvXKg7RnpCQkVQxMaTmpnC+ProsJgPvwcEitj993quvbQbBjvwEBMaG6JHWF48WKhK+5BqmFSdqEqbFCFdvYykjQr1HbYD9M/qVZwAgeovAfhRMN8QXltUwgP5x9P9UkXWZ9e+umtUoaVGMShbw4NbPUs7DieFbt4Vm+F0i7O52fqNpSa1YyJucWz2HagoNbyU//9Lr6/aIx7rpJH7Bla/mTyUzqg71DVomEIC0OJ7YdqYGLpHHf2TflmQ3doNHJTKuwqyjfmNjUqQuG0uIsP8S0QGa69FTgzslvGYHuEjTzdg6RazpNcxZao1h2Ch+YOLHKpkoExpmy3ZjbWjjg56Nke91K405H+/5S/o3GiziIN4+2rmiYIZHwwHp2y3Kbu/ySnvTnT6XcA3sfs+QM8q4YeRaOeGeCq0It+6+mLG2EN0n02eKqXQpiNmSwtfFk99ZdjC/wXB4t6zWQS4wMzw2M4Yien/GDfgwLbSj6dVxDZlQej7wwjlKWyqPiAip7VWMh2YhwUxpX0q0u1frv844H1vSIRgXyDik694gg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
