apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCEgSIGv4IP1o81IoY2m0NLUqKkHIHmNYoJB7uVzbGWqpw4hCu0tCTRi4+oOtQ/iGqUxjNU9xdtF+zZIcrnu8ajgKb17pdZ9afCy9FT9Gm7ZFArvKU8Dm1FiwkCtUa74KjYZgoRwDl/jnsQ5TL3yFNCj1wBAFbzuvHzv6h1hJfAAOtMi2rVQuXll+UhF99xZAc87BviUbb3i2z3seWDvo0/orxuRkM4ydpphQ9TEvjE73K5dqfR1n3zbXrsSyT+U+sXYtVRnXKi1DXRelZ0QpEjmYpuyQ3v3zxqXbqX4mQciXO6bpuKuw9BKlKjKz0b1luMPLFZiA45xImRmCVDepkoDr7WvlE9CmvASfnVBOVQoHuP6HUh30vWHMLDFihw7Bftqg5xEBixFT1qmWh4I41ChxX2yKqZwAjTE69kEFTR+2XB80sBBogcfrfwu+Kuh8pJBgXhs4eeRO4shZ/feGC9LoLAqf6bT5j+/S+dLoABwKz3g+DBydaRQ8L0zrRAY7bL1t06jBr14lJ/nDvbBO1VzxNqQTFtLSBMSgseytZVp3QDPeqCHzmG4qcquSt1mTQzhW0oqTXfqjNNGmagQfJd+hVc9odgkZDotxCptyGbileVsPa8/P0LQVQQVlxk5xhRGhaGYrAPc42utDbGJMULJxSwH6Djx6NPmvw9iCxVD0X8tOGVNffdBVYusR1oAjrc6KvjTfpY4BHAeUONugypAyMuiw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
