apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCreWuAuqCk+Zcw9OLil9SKaH5uVshGRQ8jZfqk8BSB5IYBI+rGSwcXeVi8I7DH0igxtaUoGO5/MYdyjTp1Z0IGurvOMYkAtYhMJAIP0PchMdj+yWgk0eFfa+cUYhofM6PX673hRWuC8Qh2BUbc3N8x0qUjJdIikR8Flj6MGSm+h5Bmi32RouT+jbQX8iGcCECI4j+n1dkajxvlMdQyU5hQ/29y/P0lpufj7T09LV0XuvxLxwPvMrYQQqNl4pX5Spwt7/dqTi9ZztpZK01dq8Hua7M4McVKCwVSgkaB9JM8IsNQETakditJPSNjzxO/3j2DKf9lghhoIyI5CKBptIf8aSSqiV2oVbkPd/OUKZgmbXcInTLRGqFm/NUf4rimlKc7ephOj6xmIL2nIqbo3qG0AxZymJF5JPl+clL5bgjuJRc2WmOr6DYdaX9SzKRAX1F/L4t2lOx78IdWIkGkMJegWLqcrUWN9Vu2C9uPnsafDMGnt4tiBD9kDRE87qJ44Hj3AsZHC7TXy+8zXOg+HZfs/7MZkZe8PQ4VtLHDvplfuu4LqCzRS0o9gGtIN3KyZtVD1F+yXIOBUBY+pw9qei+GdOzmB4mofEGVmqDNcaiBjzipbIl/iQ3m1xTgxsXew036djaE6CtfRJFP1VBH2k7mWc0WwLAaIrzQ+z5W7pYRY6fQXTeBvOCmC4zDvqvOhKtmlU+mWP6r6XIkwGcfik71BGckzg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
