apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAvZkuW5mP8Ll6tujxKPiGoKeWRMND4KkiYOzOZ7YTNgP+yoCD7j/z2/JVT6cs1DornD8+tPX21rDd/wkEM75UQfaCCyfFg0JclxLUWyXKEAYli9KbWlofy9QKljOhnrMOGMHaeyyuA4sgBFmNyQ0Te3QmFUfZeASEqFPY8e56oFl2zwuk6/EqBO1fvzW9M7mZ4fE14xas26EgW/0TLCEwqsD4qSOFcBQqdKEGE0XIyQag9TxEkkvAki+nHxvTb1/u9wvhSHMSAMQCPdhJFHtICnz4kdzr+UTETlR2gnMEjNlDaOp+s65pV2BZ62EPKvj0c5p3mKQ5Hf/IRQTLa2yKZuAL6QLugAZptJ0DaUCgj7SdESQdFTVbBmFtnCx+428CfcM1kOQoBUxF0qa4/IIWyyg4PkjtadBc22eR7Ls842EwWJ/sZYwA8KWNTTMDKzMWw6igOF2HuafgmRgkbH26Rs/VVCwwiut2JrnGKtJkSUCQUYOxDy7oc38lv3Wa4TQQjFxlAek4tAQFy1We6rM1ff9VFGQvFHWDggDXNiNlmeFzEs+3uUQySuL8TqgCcG8ZCtnVxIyTccd8o2+nrv9+mpLJAsGxeBIAWZMqsBYLmvZuRJ/Wn/XVXawXQdRCrUH50/4YiexYhuHBGbPN7BucQ5VqJLt93D1gCbCqGiC1mEySI8qE+iBA0PXWxOFz2ktkAj+fWMid9tK2YAlxH/LY2tavD/Q==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
