apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB2/xU9uZgzuKGutmkz9pBVYcVUiPjot+J/u2T/oNIS39NVFeWJdPspXekQYGlRAE1Y5OEz6sbnRbM20culTFdn4Y9wscaG2ofsVHI671uMAcvQB335RrcM+7kd9tDjxcuk5yMgNAy3XKTXbyD5nTbboBCW5S1fnyIpj42WpvW/cH5+1V0wEocR0eziJxSGZ7Cy+ij2gYLoucnbwwfCY5XikyCZymcoyBcfzQKAH/nfoCfs5bWZk1Vxu/WjvbAhOU84k25D64Ba3HsrvLeiV0ua3bp6DpMT8XoAz9gmIMczOlAEnvpomS0SsgRMi+fM5X2JVgP9MoEEF7ivAqVlK1faaz87bbqR9gwAjnGnjQNy5HIz+Txago5wOAvaCPhDIinxNRMnjJw/n5HPlprEsQ1a+Qad7ffaMWPy8y33gx+/qmCzEivqxJdQT75zbyj84erES55qwU7mPT/cCPlwTIg/Yvyz4yEzvt4S9IHUkEAz9cySBXg/n5Majqyxee0uqTcQpCFCpupT+mwUfwRtWO0K45KgCErmTH6SDboPD1T0a45uDYuA2EpvJhonXhZU/XnROilgNSZ4QIhprEZN2K63lpzCsJScG56msF6oWffrVaByO1qEtzdwddrFJcD0qCelDiEGFHZEquMAqvsrBlffv8/4bhMwb8b/I9oJb9mSdjt2048kUetrqnpdR4Zvyv7XC+ymK0eu7/cFOrI1F1uh+4NkHQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
