apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: backend-app
  namespace: stage
spec:
  port:
    targetPort: 4021
  to:
    kind: Service
    name: backend-app
    weight: 100
  wildcardPolicy: None