apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
 labels:
   machineconfiguration.openshift.io/role: worker
 name: 99-zzmytest-mc
spec:
 config:
   ignition:
     config: {}
     security:
       tls: {}
     timeouts: {}
     version: 3.2.0
   networkd: {}
   passwd: {}
   storage:
     files:
       - contents:
           source: 'data:text/plain;charset=utf-8;base64,IyBEaXNhYmxlIHJhdGUgbGltaXRpbmcKUmF0ZUxpbWl0SW50ZXJ2YWw9MXMKUmF0ZUxpbWl0QnVyc3Q9MTAwMDAKU3RvcmFnZT12b2xhdGlsZQpDb21wcmVzcz1ubwpNYXhSZXRlbnRpb25TZWM9MzBzCg=='
           verification: {}
         filesystem: root
         mode: 420
         path: /etc/systemd/journald.conf
   systemd: {}
 osImageURL: ''
