apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
 creationTimestamp: '2021-08-09T13:05:14Z'
 generation: 5
 labels:
   machineconfiguration.openshift.io/role: worker
 name: 99-zzmytest-mc
 resourceVersion: '130246'
 selfLink: /apis/machineconfiguration.openshift.io/v1/machineconfigs/99-zzmytest-mc
 uid: c13921ba-4dc5-47ec-8ea7-f6ef48b47b45
spec:
 config:
   ignition:
     config: {}
     security:
       tls: {}
     timeouts: {}
     version: 3.2.0
   networkd: {}
   passwd: {}
   storage:
     files:
       - contents:
           source: 'data:text/plain;charset=utf-8;base64,IyBEaXNhYmxlIHJhdGUgbGltaXRpbmcKUmF0ZUxpbWl0SW50ZXJ2YWw9MXMKUmF0ZUxpbWl0QnVyc3Q9MTAwMDAKU3RvcmFnZT12b2xhdGlsZQpDb21wcmVzcz1ubwpNYXhSZXRlbnRpb25TZWM9MzBzCg=='
           verification: {}
         filesystem: root
         mode: 420
         path: /etc/systemd/journald.conf
   systemd: {}
 osImageURL: ''
