apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: backend-service
  namespace: stage
spec:
  port:
    targetPort: 8081
  to:
    kind: Service
    name: backend-service
    weight: 100
  wildcardPolicy: None