apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/part-of: full-stack
  name: frontend-app
  namespace: stage
spec:
  ports:
  - name: http
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app.kubernetes.io/name: frontend-app
    app.kubernetes.io/part-of: full-stack
status:
  loadBalancer: {}
