apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: frontend-app
  namespace: stage
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: frontend-app
    weight: 100
  wildcardPolicy: None